### ISSUE TITLE
Add support for Cucumber Expressions

### ISSUE THREAD

**Issue by aslakhellesoy** [cucumber/cucumber-jvm#1041]
## Summary

[Cucumber Expressions](http://docs.cucumber.io/cucumber-expressions/) is a new alternative to
Regular Expressions, which is easier to read and write, and less daunting.
## Expected Behavior

Step Defintions that don't start with a `^` or end with a `$` should be interpreted as a Cucumber Expression:

``` Java
@Given("I have {n} cukes in my belly")
```

Alternatively we can decide to use regular expressions if the string uses `/` delimiters:

``` Java
@Given("/I have (\\d+) cukes in my belly/")
```

Whatever mechanism we choose to differentiate is likely to break existing step definitions, so we'd have to make a new major release and document how to migrate.

Snippets for undefined steps should use Cucumber Expressions, and not Regular Expressions. We want users to start migrating, and if we can avoid it we'll not generate snippets with regular expressions. (Well, we might if enough people want it). The `cucumber-expression` library can already generate expressions from text.

Finally, the current `Transform` logic should be deprecated and the logic built into the `cucumber-expression` library should be used instead.
## Context & Motivation

Having to use Regular Expressions is one of the most common complaints against Cucumber. Other clones of Cucumber who support something similar to Cucumber Expressions seem to have happier users!

**Comment by billwright** [comment]
This looks great! I tried to see what versions supported it but this link
in the documentation (http://docs.cucumber.io/cucumber-expressions/) seems
to be broken:

http://docs.cucumber.io/standard-library.adoc#implementations

Also, the documentation has this text:

You may have a Color class that you want to use to capture the red part of
the step, but unless you register a transform for that class, Cucumber
won't be able to recognise that. Let's register a transform for Color:

But the Java example below uses the Currency class and not the Color class.
The Javascript and Ruby ones use Color. Just in case you want to correct
the documentation.

Bill

**Comment by aslakhellesoy** [comment]
I just pushed a fix - better now?

**Comment by vincenzovitale** [comment]
Are Cucumber Expressions already supported in an official release? If not, how can we try them out? I cannot find any explanation on how to integrate them.

Thanks,
V.

**Comment by vincenzovitale** [comment]
Is there any version already supporting this?

Thanks,
V.

**Comment by aslakhellesoy** [comment]
The Cucumber-Expressions library is [implemented](https://github.com/cucumber/cucumber-expressions-java), but not integrated into Cucumber-JVM yet. That's why this ticket is open.

**Comment by vincenzovitale** [comment]
Thanks for the fast reply!
Is it maybe available in a snapshot version upload in a maven repo somewhere? 'd love to check them out

**Comment by aslakhellesoy** [comment]
No they're not integrated yet

**Comment by brasmusson** [comment]
No there no Cucumber-JVM version where cucumber-experssions has been integrated, it does require a quite substantial amount of work to do that - work that has been started but it is still WIP.

**Comment by vincenzovitale** [comment]
Ok, thanks guys for the Speedy Gonzalez reaction. Will use normal reg exp for now and move to it later.

Cheers,
V.

**Comment by akozhin** [comment]
Waiting for integration!

**Comment by aslakhellesoy** [comment]
Thanks for waiting!

**Comment by acooper106** [comment]
How would you use cucumber expressions for something like this
"^the client has an account balance of \\$([\\-\\d,\\d+\\.\\d+]*)$"

The links on this post don't work anymore but I found this: https://docs.cucumber.io/cucumber/cucumber-expressions/

**Comment by mpkorstanje** [comment]
Heya, you're better of asking further questions on Slack of the mailing list. Maintainers don't scale. :D

1. `the client has an account balance of ${bigDecimal}`
2. Regular expressions and Cucumber expressions are both supported.
3. Because XStream was removed your regular expression won't be transformed into a big decimal straight away. You'll have to register it as a parameter type. 
4. [Version 4.2 supports anonymous parameter types which will make a best effort attempt. 
](https://cucumber.io/blog/2018/10/31/announcing-cucumber-jvm-4-2-0)

**Comment by acooper106** [comment]
I did try 4.2.0 which works with my steps from cucumber 1.x.x without any changes but I'm waiting for the mutation plugin and the pro-plugin to also be updated in order to use 4.2.0. Until then I would like to have this working with 3.0.2 

the client has an account balance of ${bigDecimal} doesn't seem to be working with v3.0.2
My reg ex covered all my scenarios that uses $20,000.50, $0.00 and $-1.00  
How do I get my reg ex to work in this new version?

**Comment by mpkorstanje** [comment]
Ah. Maybe it's all lowercase. Check the docs.
