### ISSUE TITLE
How to instantiate “Step” scope bean in Cucumber Testing?

### ISSUE THREAD

**Issue by DinkarKolhe** [cucumber/cucumber-jvm#1089]
## Summary

**How to instantiate "Step" scope bean of spring in Cucumber Testing?**

SpringJUnit4ClassRunner uses @TestExecutionListeners to instantiate the step scoped beans for testing purpose.

I am trying get this behavior in Cucumber. Cucumber uses a @RunWith(Cucumber.class)

Is there anyway we can instantiate step scope bean?

Thanks in advance

## Expected Behavior

Given X Bean is instantiated with "STEP" scope in spring configuration
When X bean is autowired in cucumber stepDefinition class for testing
Then X bean should instantiate with "STEP" scope.

## Current Behavior

Bean is not instantiating and throwing error as given below

_Scope 'step' is not active for the current thread; consider defining a scoped proxy for this bean if you intend to refer to it from a singleton; nested exception is java.lang.IllegalStateException: No context holder available for step scope_

## Possible Solution

We should extend the features of the SpringJUnit4ClassRunner in cucumber

## Steps to Reproduce (for bugs)

1. Define bean with scope "step" in spring configuration
2. Autowire same bean in your step-definition file
3. Use that bean in your steps definition methods
4. Its not getting instantiated and failing with provided error.

## Context & Motivation

I am working on SpringBatch and using Partitioning approach. we have defined our beans with STEP scope. For the testing of the batch we are using the SpringJUnit4ClassRunner with
 @TestExecutionListeners({DependencyInjectionTestExecutionListener.class,
  StepScopeTestExecutionListener.class})

I am trying to implement in BDD format using the cucumber.  but the instantiation is failing with the above given error.

## Your Environment
Local as of now

* Version used:
                <org.springframework.version>4.1.6.RELEASE</org.springframework.version>
		<spring.batch.version>3.0.1.RELEASE</spring.batch.version>
                 <junit.version>4.11</junit.version>

                   <dependency>
				<groupId>info.cukes</groupId>
				<artifactId>cucumber-java8</artifactId>
				<version>1.2.5</version>
				<scope>test</scope>
			</dependency>

			<dependency>
				<groupId>info.cukes</groupId>
				<artifactId>cucumber-spring</artifactId>
				<version>1.2.5</version>
				<scope>test</scope>
			</dependency>
			
			<dependency>
			  <groupId>info.cukes</groupId>
			  <artifactId>cucumber-core</artifactId>
			  <version>1.2.5</version>
			</dependency>
			
			<dependency>
				<groupId>info.cukes</groupId>
				<artifactId>cucumber-junit</artifactId>
				<version>1.2.5</version>
				<scope>test</scope>
			</dependency>
			
			<dependency>
			  <groupId>info.cukes</groupId>
			  <artifactId>cucumber-jvm</artifactId>
			  <version>1.2.5</version>
			</dependency>
			
			<dependency>
			  <groupId>info.cukes</groupId>
			  <artifactId>cucumber-jvm-deps</artifactId>
			  <version>1.0.5</version>
			</dependency>
			
			<dependency>
			  <groupId>info.cukes</groupId>
			  <artifactId>cucumber-html</artifactId>
			  <version>0.2.3</version>
			</dependency>
			<dependency>
			  <groupId>info.cukes</groupId>
			  <artifactId>gherkin</artifactId>
			  <version>2.12.2</version>
			</dependency>

			<dependency>
			  <groupId>info.cukes</groupId>
			  <artifactId>gherkin-jvm-deps</artifactId>
			  <version>1.0.3</version>
			</dependency>

* Operating System and version:
         Windows 7 Enterprise
          Unix
          Linux
* Link to your project:

**Comment by brasmusson** [comment]
In Cucumber-JVM it is not the JUnit runner (`@RunWith(Cucumber.class)`), but the [ObjectFactory](https://github.com/cucumber/cucumber-jvm/blob/master/java/src/main/java/cucumber/api/java/ObjectFactory.java) for the Dependency Injection container (for Spring the [ObjectFactory](https://github.com/cucumber/cucumber-jvm/blob/master/spring/src/main/java/cucumber/runtime/java/spring/SpringFactory.java) in cucumber-spring) that is responsible for managing all aspects for the Dependency Injection. Therefore the SpringJUnit4ClassRunner and its features cannot be used directly together with Cucumber-JVM, but the features in question need to be re-implemented in the [ObjectFactory](https://github.com/cucumber/cucumber-jvm/blob/master/spring/src/main/java/cucumber/runtime/java/spring/SpringFactory.java) of cucumber-spring.

**Comment by mschwehl** [comment]
I have registered the scope-bean by myself

http://stackoverflow.com/questions/26422470/good-practice-to-pass-variables-between-cucumber-jvm-steps/41244848#41244848

**Comment by DinkarKolhe** [comment]
Thanks @mschwehl but we are using the Spring Batch Partitioning and have StepScope defined all where. Its in stable state and wont be able to touch with new experiments. Its a old project and we are trying to have BDD in place so we are converting junits to Cucumber. 

Can you please help me with Stepscope implementation if possible?

I tried below things but spring factory throwing error while loading.
Caused by: java.lang.IllegalStateException: No context holder available for step scope

I tried your implementation like below.
ConfigurableListableBeanFactory beanFactory = ((GenericApplicationContext) applicationContext).getBeanFactory();
      beanFactory.registerScope("step", new StepScope());

      ABC abc = applicationContext.getBean(ABC.class);



Bean Configuration
@Bean(name = "abc")
@StepScope
public ABC getABC(){
return new ABC();
}

Note : StepScope is a scope type provided by SpringBatch.

Thanks again and correct me if i am wrong at any place

**Comment by DinkarKolhe** [comment]
@brasmusson  Thanks for responding on this.
I did not find cucumber-spring to raise a issue so i did it here. Can you please help me the project link for cucumber-spring, if you aware ?

**Comment by brasmusson** [comment]
@DinkarKolhe 
> I did not find cucumber-spring

Cucumber-spring is a module in this project (the [`spring`](https://github.com/cucumber/cucumber-jvm/tree/master/spring) directory). My point is that even though the JUnit runner class `SpringJUnit4ClassRunner` has the behaviour you want, does not mean a) that it is the JUnit runner class of Cucumber-JVM [`Cucumber`](https://github.com/cucumber/cucumber-jvm/blob/master/junit/src/main/java/cucumber/api/junit/Cucumber.java) (as in `@RunWith(Cucumber.class)`) that need to be changed, or b) that it is easy to fix (just because `SpringJUnit4ClassRunner` has the behaviour)

> to raise a issue

As the [Readme](https://github.com/cucumber/cucumber-jvm#how-soon-will-my-ticket-be-fixed) says, the best way to have a feature implemented it to implemented it yourself and send a pull request. Do you take that challange? (I have already pointed to the class that needs to be changed, [SpringFactory](https://github.com/cucumber/cucumber-jvm/blob/master/spring/src/main/java/cucumber/runtime/java/spring/SpringFactory.java))

**Comment by DinkarKolhe** [comment]
@brasmusson , SpringJUnit4ClassRunner has the behavior and provided by Spring for testing. They have used some listeners. 
1. Cucumber-Spring can adjust this in the jar to handle this scenario
2. Create another cucumber runner to comply with SpringJUnit4ClassRunner something like SpringCucumberRunner, which will provide more functionality for spring framework.

Frankly speaking, I feel like it will be little hard for me to come up to this level of implementation. We need to understand spring framework. I wish i could have contribute but as of now, dont want to take risk on this.

I will share the scenario so someone from the community can take it further.

Thanks a lot for your offer, support and help.

**Comment by DinkarKolhe** [comment]
@brasmusson @mschwehl 

Good news to share that, By exploring some options i have made it workable for now.

Below is my workaround

Bean Configuration
@Bean(name = "abc")
@StepScope
public ABC getABC(){
return new ABC();
}


@ContextConfiguration(classes = AppConfiguration.class, loader = AnnotationConfigContextLoader.class)
public class StepDef {

@Autowire
ABC abc;

public StepDef{
StepExecution stepExecution = getStepExecution();
StepSynchronizationManager.register(stepExecution);
}

}

I am not sure how correct is this implementation. I have initialize the StepExecution to load my configuration in stepDef Constructor so my AutoWiring can work properly and i can run my test against it. 
I need to follow same approach for all stepDef , may be i will write a super class and implement that in super constructor.

Do let me know if you see any concerns. 

Thanks again

**Comment by brasmusson** [comment]
@DinkarKolhe 
> another cucumber runner to comply with SpringJUnit4ClassRunner something like SpringCucumberRunner

There can be no such thing as a SpringCucumberRunner, it is _impossible_.

JUnit runners (like SpringJUnit4ClassRunner) assume that the test are methods of the runner class, and that it is the runner class that are responsible to set up things before, run the test method, and tear down afterwards.

None of these assumptions holds in case of using Cucumber. The "JUnit runner" of Cucumber does only start up the Cucumber Runtime (and it monitors the Cucumber runtime to be able to send notifications so that JUnit listeners like Eclipse, Maven surefire etc. thinks that JUnit tests are executed), it neither know if Java is used (it could be Scala, Groovy etc), nor if Spring is used (it could be Guice, PicoContainer etc).

The Cucumber Runtime also does not know if Java or Spring is used, it interacts with the Cucumber Backends on the classpath (for instance the Cucumber Java Backend). The Cucumber Java Backend does not know if Spring is used, it searches the callspath for ObjectFactories and interacts using the same interface regardless if it was the SpringObjectFactory of another ObjectFactory that was found.

So any functionality related to Spring in Cucumber has to be implemented in the SpringObjectFactory, because it is only it that knows of Spring at all.

I do not use Spring or Spring-batch myself, so I do not know any details of what need to be changed to fix this issue (if there is something to be fixed, that is).
