### ISSUE TITLE
Duplicate scenarios executed when running single feature file line number with command line tags

### ISSUE THREAD

**Issue by temyers** [cucumber/cucumber-jvm#1101]
## Summary

If you specify `@CucumberOptions` to point to a single line in a feature file, specifically a single Example row, and execute the tests, specifying command line tags then the incorrect number of scenarios are executed.

## Expected Behavior

```
Given the feature file: 
'''@example
Feature: Example

  Scenario Outline: Running examples in parallel
    Given I want to run a scenario example in parallel
    And I am using the parallel plugin
    And this is the <num> example
    Then there should be a total of <total> scenarios run

    Examples:
      | num | total |
      | 1   | 2     |
      | 2   | 2     |
'''
And the JUnit test runner:
'''
@RunWith(Cucumber.class)
@CucumberOptions(strict = true,
features = {"C:/Users/kevin (ch)/Documents/cucumber-parallel-test/src/test/resources/features/example.feature:13"},
plugin = {"json:target/cucumber-reports/2.json"},
monochrome = false,
glue = { "com.github.kevbradwick" })
public class Example_02IT {
}
'''
When I run the script: mvn clean verify -Dcucumber.options="--tags @example"
Then the following output should be generated:
'''
Running Example_01IT

1 Scenarios (1 passed)
4 Steps (4 passed)
'''
```

## Current Behavior

When executed using `mvn clean verify -Dcucumber.options="--tags @example"` then all examples in the scenario are executed, rather than the single example as expected.
```
Running Example_01IT

2 Scenarios (2 passed)
8 Steps (8 passed)
```

If you do not specify command line tags, `mvn clean verify` then the scenarios are executed as expected.

## Steps to Reproduce (for bugs)

1. `git clone https://github.com/kevbradwick/cucumber-parallel-test`
2. `cd cucumber-parallel-test`
3. `mvn clean verify -Dcucumber.options="--tags @example"`
4. Scenarios are executed 4 times
5. `mvn clean verify`
6. Scenarios are expected twice (expected)

## Context & Motivation

Originally raised under:
https://github.com/temyers/cucumber-jvm-parallel-plugin/issues/94

The parallel plugin does not control execution, rather generates JUnit runners only.

## Your Environment

Execution environment:

```
$ mvn --version
Apache Maven 3.3.1 (cab6659f9874fa96462afef40fcf6bc033d58c1c; 2015-03-14T04:10:27+08:00)
Maven home: /Users/tim/tools/maven/apache-maven-3.3.1
Java version: 1.8.0_40, vendor: Oracle Corporation
Java home: /Library/Java/JavaVirtualMachines/jdk1.8.0_40.jdk/Contents/Home/jre
Default locale: en_AU, platform encoding: UTF-8
OS name: "mac os x", version: "10.12.3", arch: "x86_64", family: "mac"
```

**Comment by brasmusson** [comment]
Base facts:
* It is not possible to filter both on tags and on feature lines at the same time. Using something like `-Dcucumber.options="--tags @foo classpath:features/example.feature:13"` will result in `java.lang.IllegalArgumentException: Inconsistent filters: [@foo, 13]. Only one type [line,name,tag] can be used at once.` This is a property of Gherkin v2.12.2 which currently is used by Cucumber-JVM and is doing the filtering of the feature files (#1035 is intended to upgrade Cucumber-JVM to a new Gherkin version).
* Having a runner class with `@CucumberOptions(tags = {"@bar"})` and then using `-Dcucumber.options="--tags @foo"` replaces any tags setting in `@CucumberOptions` (`@bar` in this case) with `--tags @foo` 

Because it is not possible to use both tags filtering and line filtering at the same time, the `-Dcucumber.options="--tags @foo"` does also (very intentionally) clear any line filters from `@CucumberOptions` (to avoid the IllegalArgumentException above).

A consequence of this is that it is not possible to use tags filtering (of name filtering) from the command line (with `-Dcucumber.options`) when using the cucumber-jvm-parallel-plugin (since it used line filtering in the generated runner classes). It is nothing that can be done about this until Cucumber-JVM is updated to a newer Gherkin version.

**Comment by temyers** [comment]
Ok thanks for the clarification.

**Comment by shash431** [comment]
Hi temyers,
    Please if there is a way to generate a separate runner for each tag by passing the values in the plugin <tags>...</tags> and in short if i have to generate a runner for each tag to be excuted what should be the pom content also please let me know the syntax for instance i have the below tags : 

@smoke,@sanity,@smoke3,@functionality .... in this case what should be the content of tags in temyers plugin to generate separate runner for each tag
...please do mention the tag that should be passed for the above scenarios since i tried all the possible ways of passing tags

**Comment by gogonutsss** [comment]
@brassmusson now that cucumber-jvm 2.1.0 is updated to gherkin 4, should we expect to be able to use options from the command line ( -Dcucumber.options) combined with the cucumber-jvm-parallel-plugin? 

What we need to be able to do is to take advantage of parallel runner plugin with the ability to set on command line more complex options in tags like, find and run in parallel all tests having both @this AND @that tags on them:

"--tags @this --tags @that"

**Comment by brasmusson** [comment]
@gogonutsss With Cucumber-JVM v2.1.0 you should use [tag-expressionshttps://github.com/cucumber/cucumber/tree/master/tag-expressions#tag-expressions) to define complex tag filtering. It should also work with the cucumber-jvm-parallel-plugin.
