### ISSUE TITLE
Do we have an option to use OR statement in the gherkin file!

### ISSUE THREAD

**Issue by RajAsapu** [cucumber/cucumber-jvm#1184]
Note : I understand that this can be implemented thru java code.

I have a scenario to create a record in my application which might create a record if it doesn't exist or it could say that its a duplicate which is also a valid output. As i run the tests on the docker container , when a new change comes a new image would be created and tests run on that . If no change exist it might use that container for multiple test runs. So to handle this scenario i would like to use something with OR . 

Example : 

Given the user logs into the application
And    the user navigates to the create record
When  the user enters details
And     submits the form
Then   the application should display a success message as 'record created successfully'
Or       the application should display a message as 'record is a duplicate of the existing record'

**Comment by aslakhellesoy** [comment]
Please use the [support](https://cucumber.io/support) forums for questions and discussions. We use GitHub issues to track bugs and contributions exclusively.

**Comment by RajAsapu** [comment]
@aslakhellesoy I was thinking to propose it as a feature.

**Comment by aslakhellesoy** [comment]
OR implies non-determinism, and we won't be adding support for that in Cucumber. 

All scenarios should be deterministic - given a certain context, when something happens, then the outcome should be something expected.

Cucumber is designed to be used in an environment where you're in full control of the context. If this is hard, make it easy with patterns like "ports and adapters"

**Comment by Richie5555** [comment]
Personally I would like to see an Or Key word, but not in the above context. I agree with the deterministic nature of a Scenario, but I think it could add value by increasing readability for Scenario outlines instead of Example Tables i.e.

Feature: Borrowing from a libary
Scenario Outline : Returning an item late 
    Given I have borrowed a 'Book'
    Or I have borrowed a 'DVD'' 
    When I return it after the due date
    Then I will be fined £5

This would then generate 2 Scenarios which are both deterministic and would be syntactically the same as:  

Scenario Outline : Returning an item late 
    Given I have borrowed a '<item>'
    When I return it after the due date
    Then I will be fined £5

   Examples:
  | item  |
  | Book |
  | DVD  |

Or would not replace examples... as it would be difficult to work with when there are more parameters, but to me the first is more readable by people not so up to speed on Gherkin.
