### ISSUE TITLE
Running by feature path:line number using cli runs all scenarios

### ISSUE THREAD

**Issue by abhisheksreepal** [cucumber/cucumber-jvm#1234]
## Summary
Running by feature path:line number using cli runs all scenarios

## Expected Behavior
Running by feature path: line number should run the only scenario of specific feature and scenarios falling under line numbers

## Current Behavior
Lets say, we have 2 features under resources folder and I would like to Run 1 scenario of a particular feature by feature path as mentioned below

[uiwebtest/src/main/resources/features/AppLogin/Login.feature:5, --plugin, pretty, --plugin, html:uiwebtest/output/cucumber/html, --plugin, json:uiwebtest/output/cucumber/json/cucumber.json, --plugin, rerun:run.txt, --glue, com.cuke.webrtc.tests, uiwebtest/src/main/resources]

Actual Result: All scenarios are run 
Expected Result: Only 1 scenarios should run

~~~
~~~

## Possible Solution

Possible Fix:  In this file [LinePredicate](https://github.com/cucumber/cucumber-jvm/blob/d18446f8da47a778fa65b9c0ca77019740879a21/core/src/main/java/cucumber/runtime/LinePredicate.java) , For apply method, we should return false if lineFilters does not contain picklePath as key
if (!lineFilters.containsKey(picklePath)) {
            return false;
}

Note: Tested locally and is working fine.

## Steps to Reproduce (for bugs)

1. 
2.
3.
4.

## Your Environment

Running cucumber tests using cli
* Version used: 2.0.1 snapshot
* Operating System and version: Mac OS
* Link to your project:

**Comment by mpkorstanje** [comment]
> Possible Fix: In this file LinePredicate , For apply method, we should return false if lineFilters does not contain picklePath as key

This is intentional. It allows `path/file.feature another_path/file.feature:8` to be correctly handled. 

You are passing `uiwebtest/src/main/resources` as a feature path. As `uiwebtest/src/main/resources` is a parent directory of `uiwebtest/src/main/resources/features/` all feature will be picked up.

**Comment by abhisheksreepal** [comment]
@mpkorstanje  To be precise, 2 features are under features folder(under child folders). Let me show you the structure.

Just for e.g.  
"uiwebtest/src/main/resources/features"
|--uiwebtest
|---main
|-----resources
|--------features
|----------AppLogin
|-------------Login.feature
|----------Home
|-------------Home.feature


As you see in command line, I am  passing feature path as

> uiwebtest/src/main/resources/features/AppLogin/Login.feature:5

**Shouldn't only that feature run ?**

[**uiwebtest/src/main/resources/features/AppLogin/Login.feature:5**, --plugin, pretty, --plugin, html:uiwebtest/output/cucumber/html, --plugin, json:uiwebtest/output/cucumber/json/cucumber.json, --plugin, rerun:run.txt, --glue, com.cuke.webrtc.tests, uiwebtest/src/main/resources]

**Comment by abhisheksreepal** [comment]
ok got it. So Having multiple resource folders will result in the issue! Sorry . Will remove " uiwebtest/src/main/resources" and try again

**Comment by mpkorstanje** [comment]
It is intended behavior. :)

[**uiwebtest/src/main/resources/features/AppLogin/Login.feature:5**, --plugin, pretty, --plugin, html:uiwebtest/output/cucumber/html, --plugin, json:uiwebtest/output/cucumber/json/cucumber.json, --plugin, rerun:run.txt, --glue, com.cuke.webrtc.tests, **uiwebtest/src/main/resources**]

The second bolded section is the problem. You might think it is passed as glue, but it is passed as a feature path because it is not preceded by `--glue`.

You can check the contents of `RuntimeOptions.featurePaths`

**Comment by abhisheksreepal** [comment]
Thank You. Looks like I missed the second part. It's working fine.

Regards,
Abhishek
