### ISSUE TITLE
Docstring content type is not preserved into formatters

### ISSUE THREAD

**Issue by rjwittams** [cucumber/cucumber-jvm#1263]
## Summary

Doc strings no longer preserve their content type into formatters.
This means formatters can't do type dependent formatting.
This works in cucumber 1.x
## Expected Behavior
Reports with docstring content types.
## Current Behavior
Reports missing docstring content types.
## Possible Solution

https://github.com/cucumber/gherkin-java/blob/53b9552cc6b9c85161344fb38f93099639565e9b/src/main/java/gherkin/pickles/Compiler.java#L150

Here, the docstring type needs to be added to the PickleString

## Steps to Reproduce (for bugs)
Run a feature with a docstring type using json formatter. Look at the output.

**Comment by mpkorstanje** [comment]
Hey thanks for the report and the analysis!

The fastest way to get this fixed would be to send a pull request to [cucumber/gherkin](https://github.com/cucumber/cucumber/tree/master/gherkin) in the mono repo.

**Comment by rjwittams** [comment]
https://github.com/cucumber/cucumber/pull/292 - This PR is now passing the build. 
The PR for this repo depends on it.

**Comment by brasmusson** [comment]
I close the because formatters can use both the data defined in the Pickles and the data in the feature file to produce its report. The decision to include the content type of doc strings in the pickles should be based on whether it is beneficiary to have access to it when executing the test case based on the Pickle, not for the convenience of formatters. The behavior of including the content type of doc strings in the output of any Cucumber-JVM formatter can be implemented regardless of if the content type is included in the Pickle or not.
