### ISSUE TITLE
Cucumber-guice Injector specified with the runners properties

### ISSUE THREAD

**Issue by kyleroush** [cucumber/cucumber-jvm#1296]
## Summary

I would like to be able to specify the Injector I want to use inside the ```CucumberOptions``` annotation on my runner file. This way I don't have to create a separate property file for the module.

This is a problem for me since i want to several separate Injectors in the same module

## Current Behavior and Expected Behavior
For custom injectors we are required to create a properties file at the root of the
classpath. and specify one property in it .
```guice.injector-source=```

## Possible Solution
```
@CucumberOptions(guice.injector-source = "...", ...)
public class Runner {

}
``` 

## Context & Motivation
* I am using cucumber to perform my integration test.
* I want to test the same feature in multiple different enviorments which require different configs.
* I was planning on using different runners to set up and instantiate the different environments like
This is what i am doing now
```
import org.junit.BeforeClass;
//So i can test against other service that are deployed
public class DeployedTest {
  @beforeClass
  public static before() {
    //start server
    Config config = new config(...);
    Steps.setup(config) //sets up a static the static variables in my step files
  }

}
``` 
and 
```
import org.junit.BeforeClass;
//so i can test against mock services
public class LocalTest {
  @beforeClass
  public static before() {
    //mock other services 
    //start server
    Config config = new config(...);
    Steps.setup(config) //sets up a static the static variables in my step files
  }

}
``` 

I would really like if i didn't have to set static variables in my test because i feel like that is a bad practice. And to resolve that I would like to setup and specify what injector to use with my Runner.

P.S.
If having multiple runners is also a bad practice I would be interested to here others way around this problem

**Comment by mpkorstanje** [comment]
Sounds like a good idea. A few caveats:

1. The runtime options should not know about the details of the object factory. We are cheating a little with `--junit`. This should eventually be solved by creating different annotations for junit and testing.

So instead of adding a guice specific option it might be better to create an option to set environment properties. Equivalent to Javas `-Dkey=value `.

2. The environment variables override cucumber options. This should be reversed and would be a major breaking change but a good one none the less.

3. Making the properties file used configurable through a config parameters would also help e.g. `--settings=cucumber. properties`.

The order of precedence should be 

1. Commandline
1a. `--property key=value `
1b. `--settings cucumber. properties `
2. cucumber. properties
3. Environment

**Comment by brasmusson** [comment]
> The environment variables override cucumber options

@mpkorstanje AFAIK this is so that `-Dcucumber.options="<options>"` override the content of the `@CucumberOptions` annotation. Do you think that it should not be possible to use `-Dcucumber.options="<options>"` anymore?

**Comment by mpkorstanje** [comment]
The override makes sense when there is a single runner for the whole project. It allows people to do things like  `mvn test -Dcucumber.options=some/file.feature` to select specific features from the commandline. 

When there are multiple runners involved that test will be executed twice, in parallel if maven was configured that way, both possibly failing because the annotations were setup with glue configurations not intended for that feature. Even weirder would be using `cucumber.properties` in combination with the command-line. When calling `cucumber my/file.feature` while cucumber.properties contains `cucumber.options=my/` it will always all features. It defies expectation. 

When looking at this use case I think we are still missing the proper command line tool to use cucumber with java. While we could use the CLI typing out the class path of a maven project is cumbersome compared to `mvn test -Dcucumber.options=some/file.feature`. It'd be better to do  `mvn cucumber:test -Dcucumber.options=some/file.feature` and have maven sort out the tedium without reusing a junit test.

But even that is just kicking the can forward. Now I haven't figured out a good way to put this into words yet but it feels as if cucumber is missing a part. I ran into this same conceptual problem when looking to write a cucumber implementation of the JUnit5 platform. JUnits execution unit can be a single test, a class containing multiple tests,  a package containing multiple, or a project root containing multiple packages. It is a thing you can point at it in the file system.

Cucumbers execution unit isn't the glue, its not the feature either, it is a combination of glue, features, object factory, object factory settings and once cucumber expressions is finished a configuration object for parameter types. And while we can configure the glue and features pairs through cucumber options  `@CucumberOptions`, `cucumber.properties` and the environment properties are decidedly singular and override both `@CucumberOptions` and the command line. 

I guess I am trying  to say that cucumber is inconsistent in its supports for multiple runners and lacks a well defined platform and language independent execution unit. Unless Ruby already has this, then I am just unaware of it. :D


@kyleroush I reckon that for now you're better of creating separate maven sub modules for each runner.

**Comment by kyleroush** [comment]
I mean I might not be thinking big picture enough but I would be able to solve my problem enough if the properties files was configurable and if we could add an option for that while it might not be the the ideal solution (for me or for cucumber) I think it would be better then current situation

**Comment by brasmusson** [comment]
> I guess I am trying to say that cucumber is inconsistent in its supports for multiple runners

Of course. Runners are a foreign element to Cucumber, disguising Cucumber Scenarios as something they are not - JUnit tests or TestNG tests. One benefit of using them is to reuse a lot of available infrastructure (for JUnit or TestNG tests) - both in terms of notifications and reporting and in terms of triggering the execution (with the proper class path setting). But in term of Cucumber, multiple runners make not sense, each Cucumber invocation is always parametrized with the options to use (features, glue etc etc) to use in this invocation (so any runner can always be used to execute anything).

In terms of feature files and glue, there is a many to many relation. A glue defines the step definitions that can be used to execute many feature files. One the other hand can a feature file be executed together with many different glues (for instance to either execute directly towards the domain layer, or to execute end to end).

**Comment by mpkorstanje** [comment]
@kyleroush  if you can provided it I am not opposed to a PR that adds  `--settings=test-specific-cucumber. properties` to   command line and  cumber options annotation.

**Comment by kodstark** [comment]
Hi. I want to share my experience with cucumber in discussed problem. 

First I can say I have been using cucumber for few years and found it very useful. Guice integration offers nice way to  setup tests in flexible way with guice modules. I am running tests for few components which share glue code and setup code and separate instances of InjectorSource are enough to run different tests without maven / classpath tricks.

I run cucumber in IDE as junit suite with using custom runner to configure each suite with proper InjectorSource. Setting property in IDE is not good enough here as suite is not self-contained and developer needs knowledge how to run it. However proposition to improve cumber options resolve it (I use custom `@GuiceCucumberOptions`)

At Jenkins I switched from maven running suites to CLI runner (wrapped with my class) - it is mainly because of using Jenkins scripted pipeline with parallel support running tests on different nodes. Setting property is good enough for this case.

@kyleroush I posted details of this interim solution at [stackoverflow](https://stackoverflow.com/questions/35315963/cucumber-with-guice-multiple-guice-injector/40429150#40429150) year ago - I found cucumber abstractions for backend and glue code are flexible enough to fix that issue.
