### ISSUE TITLE
SingleValueConverter registered globally does not get applied to XStream

### ISSUE THREAD

**Issue by davidyscott** [cucumber/cucumber-jvm#1328]
Because `Converter` and `SingleValueConverter` are not type-compatible, and the change that added support for globally registering custom `Converter`s does not handle `SingleValueConverter`s as well.
For full context see my comment here: https://github.com/cucumber/cucumber-jvm/pull/1010/files#r172397011

It doesn't seem to be possible to work around this issue by implementing a `Converter` rather than a `SingleValueConverter` due to the way `ParameterInfo::convert` only wants a `SingleValueConverter` to work with (I don't have a solid grasp of this area so if that sounds waffle-y it's because it is!)

**Comment by mpkorstanje** [comment]
I doubt this is something that will be fixed. 

Primarily because Cucumber Expressions will handle conversion in the future (https://github.com/cucumber/cucumber-jvm/issues/1041, https://github.com/cucumber/cucumber-jvm/pull/1248) and in part because XStream does not work with Oracle JDK9 (https://github.com/cucumber/cucumber-jvm/issues/1311).

**Comment by davidyscott** [comment]
That's interesting and good to know, thank you!  #1311 does explain some of the difficulty I was having.

That said, it's a 2-line change.  If I manage to figure out my build issues, I'll see about submitting a PR for it.

**Comment by mpkorstanje** [comment]
If you're stuck on some weird problem with PAXExam feel free to ignore that. The OSGI stuff is somewhat fragile.
