### ISSUE TITLE
Cucumber test results don't display examples name or steps

### ISSUE THREAD

**Issue by Bratok17** [cucumber/cucumber-jvm#1360]
I've ran into some unexpected results running a maven project with cucumber 2.0+. I discovered when running my tests as Junit, the immediate output doesn't display the "Examples" names or steps, instead it repeats the "Scenario outline" name for each line of "Examples" table. As practice I tried running the demo project for Screenplay pattern "TODOMVC" from https://github.com/serenity-bdd/screenplay-pattern-todomvc, using cucumber-java and cucumber-junit version from 2.0.0 to 2.4.0

I've tried executing the runner with (CucumberWithSerenity.class) as well as (Cucumber.class) And this is how the JUNIT looks in my Ecplise.

Junit report in eclipse
![39549955-36517c12-4e25-11e8-8d1e-cd0c92bb2f59](https://user-images.githubusercontent.com/38926055/39632449-be2ba396-4f7a-11e8-9c65-c6b2317a4747.png)

Executing the runner using the old info.cukes dependencies (1.2.5) produce result with example names and steps as expected.

**Comment by mpkorstanje** [comment]
This is intentional.

JUnit tests form a tree structure. JUnit assumes that the leaves are the actual tests. By presenting the steps as tests as was done prior to 2.x quite a few JUnit features and integrations were subtly broken: https://github.com/cucumber/cucumber-jvm/issues/263,  https://github.com/cucumber/cucumber-jvm/issues/935, https://github.com/cucumber/cucumber-jvm/issues/577, https://github.com/cucumber/cucumber-jvm/issues/1120.

You can get the old behavior back for now by using  `@CucumberOptions(junit = "--no-step-notifications") ` but this option may be deprecated in the future. 

If you want to improve current naming you can have a look at the [PickleRunners](https://github.com/cucumber/cucumber-jvm/blob/master/junit/src/main/java/cucumber/runtime/junit/PickleRunners.java#L108). Specifically `getPickleName`.

**Comment by Bratok17** [comment]
Great, thanks for clarification. I'll take a look at picklerunners, than you for suggestion.

**Comment by Bratok17** [comment]
@mpkorstanje seems like @CucumberOptions(junit = "--no-step-notifications") is not doing anything for me :(

**Comment by mpkorstanje** [comment]
That's because I copied the wrong example. Try  `--step-notifications`

**Comment by Bratok17** [comment]
@mpkorstanje awesome, this is showing the steps executed! But as far as "Examples" names go, they are still being replaced by the "Scenario Outline" name. Any quick-fix for that, or is that where picklerunners have to come in?

**Comment by Bratok17** [comment]
@mpkorstanje Ok. Thanks for your help, really appreciate it!

**Comment by salvada** [comment]
Hi @mpkorstanje, I have a problem when running with cucumber 4.2.0 my tests. I use mvn to do it. Since I updated the version when running the tests i do see any outcome, although they are running, and also I see a huge performance problem. I tired to use the step-notifications you mentioned above to see the results when running the tests without any success I think that I made a mistake in the command line
Have you any suggestions about these two problems?

**Comment by mpkorstanje** [comment]
Yes please create a new issue with sufficient information to reproduce the first problem. The same for the second one, but also include any measurements you may have and if possible the results of a profiler.

**Comment by systemsincode** [comment]
@mpkorstanje
Can you point me to an example of how to use picklerunners? (link is broken) 
I want to uniquify? each scenario outline example execution name. I could use an Id column and ref in scenario, but I've got 100 or so example tables  to fix in that case! I guess I just need to change standard behaviour for outlines only. 
My requirement is due to reporting in to test rail will give a false positive if the last example to execute passed, as as far as the junit report is concerned this is a rerun of the same test.

**Comment by mpkorstanje** [comment]
https://github.com/cucumber/cucumber-jvm/blob/master/junit/src/main/java/io/cucumber/junit/PickleRunners.java

**Comment by mpkorstanje** [comment]
> as as far as the junit report is concerned this is a rerun of the same test.

Have a look at the implementation of the `PickleId`. It's what is used internally in JUnit to uniquely identify a scenario.

**Comment by nuwaveqateam** [comment]
thanks now my junit steps are visible.

**Comment by udayrajv** [comment]
Is there a way to do the same thing with Cucumber Ruby -  @CucumberOptions(junit = "--no-step-notifications") 
Thanks!
