### ISSUE TITLE
Unable to convert fields in data convert class

### ISSUE THREAD

**Issue by jlin412** [cucumber/cucumber-jvm#1419]
## Summary
In 1.x, I was able to convert using @XStreamConverter in any attribute when I attempt to convert fields in a data class.
In 3.x, I can convert step definition type parameter like
```
        typeRegistry.defineParameterType(new ParameterType<String>(
                "variable",
                "[^\"]*",
                String.class,
                new Transformer<String>() {
                    @Override
                    public String transform(String s) throws Throwable {
                        return convertVariableFromProperty(s);
                    }
                })
        );
```
but attempting to convert a datable cell failing:
```
registry.defineDataTableType(
  new DataTableType(
    String.class,                            // type
    new TableCellTransformer<String>() {     // transformer
                    @Override
                    public String transform(String s) throws Throwable {
                        return convertVariableFromProperty(s);
                    }
    }, 
  )
```
Error says String.Class is already a type of TableCellTransformer.

## Context & Motivation
Right now, I have to something like this to convert each field and each class.
```
        typeRegistry.defineDataTableType(new DataTableType(
                MeasureAttributes.class,
                new TableEntryTransformer<MeasureAttributes>() {
                    @Override
                    public MeasureAttributes transform(Map<String, String> entry) {
                        return new MeasureAttributes(convertVariableFromProperty(entry.get("filter")),
                                convertVariableFromProperty(entry.get("filterCriteria")),
                                convertVariableFromProperty(entry.get("searchText")),
                                convertVariableFromProperty(entry.get("delimiter")));
                    }
                })
        );
```
Is this a bug or I am doing something wrong here?
## Your Environment
* Version used: 3.0.2
* Operating System and version: Mac 10.13.2

**Comment by mpkorstanje** [comment]
As explained very briefly in the [release announcement](https://cucumber.io/blog/2018/05/19/announcing-cucumber-jvm-3-0-0) this new behavior is intentional. XStream had become completely tangled up with the implementation of cucumber-jvm, this prevented us from making any improvements, additionally it prevented others from using object mappers and annotations used in their domain.

Currently the most code efficient way to map a data table of key-values to a list of objects is to use an object mapper. This can either be XStream, Jackson or any other system. This may look like:

```
ObjectMapper objectMapper = new com.fasterxml.jackson.databind.ObjectMapper();

typeRegistry.defineDataTableType(new DataTableType(
    Grocery.class,
    (Map<String, String> row) -> objectMapper.convertValue(row, Grocery.class))
);
```
Note that you will have to do this for every type. 

Please track https://github.com/cucumber/cucumber-jvm/issues/1388 for more information.
