### ISSUE TITLE
Reusing step definitions in Spring environments for unit testing

### ISSUE THREAD

**Issue by aigloss** [cucumber/cucumber-jvm#1465]
## Summary

As a Spring-cucumber-java8 developer, I'd like to be able to prepare my Spring context for the current Scenario steps.

## Expected Behavior

When defining a Step, it'd be pretty useful to let each StepDefinition to do whatever it needs to do for the test to work. 

For instance, let's use an example scenario:
```
When I post an item with name "myItem" to the item api
Then an item with name "myItem" is saved in the database
```

In this case, to avoid having to setup a database, I'd like to mock my ItemRepository so that in the second step definition I can check if 'save' method have been called with an item named "myItem".
If this mocking action is related to the step definition, rather than to the scenario or the feature, I can effectively reuse this step along any scenario without having to worry about what needs to be set in each scenario.

## Possible Solution

Currently, steps in a scenario are executed by CucumberScenario.run method, which will create the "backend world" (in case of Spring, the application context) prior to running the steps defined. 
On the other hand, using java8, code to be executed by a step definition is defined as a lambda. 
Letting step definitions to define two lambdas, one for initialization, and one for execution, would allow CucumberScenario.run method to do some kind of "dry run", where only initialization lambdas are executed, prior to creating the backend world. This would add a lot of flexibility to developers, and, in this case, I could, for example, create a custom ApplicationContextInitializer registering a BeanFactoryPostProcessor with static methods that allow step definitions to register the necessary mocks/spies/whatever.

## Context & Motivation

One of the main advantages of using Cucumber, is the possibility of reusing step definitions. When used with Spring in a unit test environment (not integration nor e2e tests), step definitions might depend on configurations that, from a code point of view, do not belong to the step definition itself, making it more difficult and error prone to reuse those steps across different scenarios.
On the other hand, key methods, such are either private or static, making it impossible to extend the framework to get this behavior, and key classes implementations, such as FeatureBuilder, are not configurable.

**Comment by mpkorstanje** [comment]
The usecase you describe seems quite similar to the one supported by [@MockBean](https://docs.spring.io/spring-boot/docs/current/api/org/springframework/boot/test/mock/mockito/MockBean.html). So I believe the proper approach would be to reuse as much of Springs functionality is as possible. 

It is currently possible to use `@Autowired` e.g.:

```java
public class Example {

    @Autowired
    private User object;

    @Then("the user is real")
    public void the_user_is_mocked() throws Exception {
        assertThat(object.toString(), equalTo("I am real"));
    }
}
```

Likewise `@MockBean` should *just* work but unfortunately doesn't e.g:

```java
public class Example {

    @MockBean
    private User object;

    @Given("there is a User")
    public void there_is_a_User() {
        when(object.toString()).thenReturn("I've been mocked");
    }

    @Then("the User is mocked")
    public void the_user_is_mocked() throws Exception {
        assertThat(object.toString(), equalTo("I've been mocked"));
    }
}
```

The reason for this is two fold:

1. There is no spring context declared (`ContextConfiguration`, `BootstrapWith` ect)  so the `SpringFactory` falls back to some minimal default. This can be resolved by adding `@SpringBootTest` to the step definition.

2. The [SpringFactory](https://github.com/cucumber/cucumber-jvm/blob/master/spring/src/main/java/cucumber/runtime/java/spring/SpringFactory.java) does not call  
 * `TestContextManager.beforeTestClass()` 
 * `TestContextManager.prepareTestInstance()`.  
 * `TestContextManager.beforeTestMethod()` 
 * `TestContextManager.beforeTestExecution()` 
 * `TestContextManager.afterTestExecution()` 
 * `TestContextManager.afterTestMethod()` 
 * `TestContextManager.afterTestClass()` 

Instead step definitions are registered as beans in the Spring context. This had the advantage that step definitions can be auto wired into each other and constructor dependency injection just works. However it also puts the step definitions into the spring context which complicates things.
Given that step definitions calling each other is not a best practice I would not mind step definitions were no longer part of the spring context and instead treated as test instances. It would however be a breaking change.

And to further complicate matters, our current `SpringFactory` was written for Spring 4. It would be beneficial to create one for Spring 5.

So to implement this properly the following would have to be done:
 * Create a new `SpringFactory` for Spring 5.
 * Require that all step definitions created by the Spring 5 `SpringFactory` have an empty constructor.
 * Map the life-cycle methods of the `TestContextManager` to that of the `ObjectFactory`.
 * Fail when there is no Spring context declared instead of creating a default.

Would you be interested in doing this?

>  On the other hand, key methods, such are either private or static, making it impossible to extend the framework to get this behavior, and key classes implementations, such as FeatureBuilder, are not configurable.

There are currently only a few extension points, namely `ObjectFactory`, `Backend` and `Plugin`.  As explained above I believe `ObjectFactory` would be the proper extension point for this.

To support the sort of fine grained configuration you have mind in a manageable way the framework would need an internal dependency injection mechanism. The first step there is to slowly refactor the framework to use constructor dependency injection. You are however most welcome to help with this as well!

**Comment by aigloss** [comment]
Thanks  forsuch a quick response!!!

Actually I've tested the MockBean approach before posting, and you can make it work with some pretty simple configurations I've found Googling a little bit. However, using MockBean does not solve my use case.

For example, having a class with an variable annotated with MockBean, and two step definitions, would result in the bean being mocked no matter which steps appear in the scenario, which might not be what is needed.
Probably, that behavior can is fine in most cases by being preemptive and use SpyBean instead of MockBean, however, going back to my example above:
```
When I post an item with name "myItem" to the item api
Then an item with name "myItem" is saved in the database
```
there are some considerations:
- some code like 
```java
when(itemRepository.save(any(Item.class)).thenReturn('myitem');
```
should be executed _if and only if_ the second step is present
- in order to mock the behavior properly, the parameter extracted from gherkin should be accessible when executing then `when(...).thenReturn(...)` statement.

The only way I can think of having this behavior (without knowing too much about cucumber-java internals) is being able to define a step definition like:
```java
Then("an item with name \"(.*)\" is saved in the database",
     (itemName) -> { //this is the lambda that we would define with current behavior
         ArgumentCaptor<Item> savedItem = ArgumentCaptor.forClass(Item.class);
         verify(itemRepository, times(atLeastOnce)).save(savedItem.capture());
         assertEquals(itemName, savedItem.getValue().getName());
     },
     (itemName) -> { //this would allow to do necessary initialization
        ItemRepository itemRepository = mockBean(ItemRepository.class); //this would be optional if using MockBean
        when(itemRepository.save(any(Item.class))).thenReturn(itemName); // note we need itemName here
     }
);
```
With this, `CucumberScenario.run` method would:
1. execute the second lambda for each step in the scenario before building backendWorlds (A BeanFactoryPostProcessor could collect those lambdas and have them being executed when starting Spring context)
2. Build the backend worlds (i.e.: starting application context)
3. Follow steps execution as usual

Think, this would have little impact on current behavior. We would just need to modify the way StepDefinitions and CucumberScenarios are coded. First one to be able to create StepDefinitions with a new parameter (new constructor), and CucumberScenarios to introduce that additional step on 'run' method.
Sadly, since those two classes do not belong to the framework's extension points set, it cannot be accomplished without modifying the source code.

**Comment by mpkorstanje** [comment]
Even without the extension points I think you are underestimating the complexity of what you are proposing. There is no context to invoke the lambda's on until after the backend world is created. In fact, it is impossible to even get at the lambda without instantiating that particular step definition class. A feat that can only be performed by the object factory. :)

There are a few more problems too as I am not at all convinced that your use case is useful I'd rather focus on that first. 

You didn't quite explain _why_ it would be useful to have some code execute only if and only if a step is present in a scenario. Specifically it would appear that `when(itemRepository.save(any(Item.class))).thenReturn(itemName);` could return any arbitrary name as the return value is never checked. A name is checked, but that would be the name of object provided as an argument to `save`, not its return value.

If echoing name is required for correct execution of other parts of the system wouldn't a `thenAwnsers` instead of a `thenReturn` be more appropriate?

**Comment by aigloss** [comment]
> Even without the extension points I think you are underestimating the complexity of what you are proposing. 
You're probably right.

Regarding the rest of the comment, sorry for the mistake in the code, 
```java
ItemRepository itemRepository = mockBean(ItemRepository.class); //this would be optional if using MockBean
when(itemRepository.save(any(Item.class))).thenReturn(itemName);
```
should be
```java
ItemRepository itemRepository = mockBean(ItemRepository.class);
Item item = new Item();
item.setName(itemName);
when(itemRepository.save(any(Item.class))).thenReturn(item);
```
It was just an example written in the comment, anyway.
The thing is, when executing the first step, `When I post an item with name "myItem" to the item api` a post is done using 'myItem as name', and there is no chance for the second step to mock the itemRepository properly before that post is done. It's not a matter of `thenReturn`, or `thenAnswer`, it's a matter of how the steps are executed by the CucumberScenario.run method. 
Another way around would be would be to split my proposed step definition declaration into the standard Given/When/Then clauses, and a bean containing the initialization code, and the regexp associated to the step, but there is no way I can get the current executing scenario steps from Spring context. So, at the end of the day, it's a pretty useless approach.

Since there is no way to alter the order how things are executed and think that modifying the source code to allow it is far from my capabilities because of my little knowledge on the internals of the framework, think I'll just skip using this for unit testing and get stick to use it for E2E tests only.

Thanks anyway for your support.

**Comment by mpkorstanje** [comment]
You're welcome.

If you don't mind. I still don't quite understand why using Given/When/Then wouldn't work or why you need the setup bean. Or why you need the setup bean if and only if a given step is in the scenario. 

 If this were a unit tests it would look somewhat like this:

```java
// Given a working item repository
ItemRepository itemRepository = mockBean(ItemRepository.class);
Item item = new Item();
item.setName(itemName);
when(itemRepository.save(any(Item.class))).thenReturn(item);

// When I save the "foo" time
String itemName = "foo";
myItemApi.save(new Item(itemName));

// Then the "foo" item is saved
ArgumentCaptor<Item> savedItem = ArgumentCaptor.forClass(Item.class);
verify(itemRepository, times(atLeastOnce())).save(savedItem.capture());
assertEquals(itemName, savedItem.getValue().getName());
```
The `mockBean` call would have to be replaced with a `@MockBean` but otherwise it seems to cover everything.

**Comment by aigloss** [comment]
Let's see if I can explain myself better :)

For your example to work, the `Given` statement should be be something like 

`Given a working item repository returning an item with name "foo"`

otherwise, the code related to the statement would not know how to mock the item object properly. This means that I should probably have a "Given/Add" statement for each "Then/And" statement.

So, IMHO, this approach has two problems:

1. as mentioned, if there is a test checking more than one condition, I should have more than one "Given/And" statements, adding unnecessary complexity to the scenario's Gherkin
2. and most important, tests should be written by someone with a good knowledge of the code, which is definitely not desirable, since anyone with functional knowledge should be able to write test cases in Gherkin.

First point is affordable, second...don't think so.
