### ISSUE TITLE
How do we use 'Background:' and 'Scenario Outline:' keywords at the same time

### ISSUE THREAD

**Issue by PrasadNutalapati** [cucumber/cucumber-jvm#1561]
## Summary

I can't use the two keywords 'Background:' and 'Scenario Outline:' keywords at the same time
## Expected Behavior

The Scenario Outline steps should be run as a back ground to all other Scenarios given after the 'Background' and the 'Scenario Outline'.

## Current Behavior

```
Only Scenarios given after the 'Scenario Outline' steps are executing. I need the  'Scenario Outline' steps which are logging a user to a website should be executed for each scenario.

```

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Context & Motivation

I am giving steps and credentials of an User to login to a website as "Background:" which is a prerequisite for all my scenarios. This login process needs credentials which I am supplying under "Examples:" table of a "Scenario Outline:"

## Your Environment

I am using this as a part of Serenity, which is using Cucumber-core of version 2.40, cucumber-jvm-deps of 1.0.6 and Gherkin of 5.0.0 and tag expressions of 1.1.1 version.

**Comment by mlvandijk** [comment]
Afaik this is not possible. 

The [`Background`](https://docs.cucumber.io/gherkin/reference/#background) section is intended to use for setup common to all scenarios; i.e. setup that would be *the same* for all scenarios.

A [`Scenario outline:`](https://docs.cucumber.io/gherkin/reference/#scenario-outline) is intended to perform the same scenario multiple times, *with different combinations of values*.

In order to perform the scenario outline with multiple users, you would have to provide the users as part of your scenario outline / examples.

**Comment by mlvandijk** [comment]
Sidenote: Please use the [support](https://cucumber.io/support) forums for questions and discussions. We use GitHub issues to track bugs and contributions exclusively.

**Comment by PrasadNutalapati** [comment]
>>>Please use the [support](https://cucumber.io/support) forums
There is only 'community slack' channel for forum like questions. But my organization is blocking the 'chat/sms' category, though.
Sorry,
