### ISSUE TITLE
Cucumber JVM doesn't work after migration to AndroidX

### ISSUE THREAD

**Issue by VitaminPSG** [cucumber/cucumber-jvm#1567]
Tests fail from gradle
After migration Cucumber Runner fails with `cucumber.runtime.CucumberException: No backends were found. Please make sure you have a backend module on your CLASSPATH.` 

If we set `enableJetifier` property as `False` tests start successfuly, but we will faced with app compilation issues. 
This issue I've reproduced on old cucumber version `1.2.5` and new `4.2.3`.
I've created Repo with two commits where you can easely reproduce this issue:
https://github.com/VitaminPSG/Android-Cucumber-BDD-Sample/commits/master
Please see last two commits. Also one important thing that if I run tests from Android Studio they run successfely
P.s I've used command ` ./gradlew testDebugUnitTest --info`

**Comment by mpkorstanje** [comment]
I've initially moved the issue to to `cucumber-android` because I don't have a working knowledge of Android.

Anyway it seems that the project requires me to setup some Android tooling. So I'm afraid that due to a lack of time I won't be able to help you resolve this unless you can pinpoint the exact problem for me.

Might be worth noting though that the groupId has changed from `info.cukes` to `io.cucumber` and the latest version is `4.2.3`.

In this version the backends are discovered by the `[BackendModuleBackendSupplier.loadBackends](
https://github.com/cucumber/cucumber-jvm/blob/master/core/src/main/java/cucumber/runtime/BackendModuleBackendSupplier.java#L51)`. Stepping down from there you'll have to work out why the class finder is unable to discover any subclasses of `Backend`.

**Comment by lsuski** [comment]
As it works with Android Studio and not with Gradle it seems like some packaging/classpath issue

**Comment by lsuski** [comment]
There is some issue with loading resources from classloader. When running from gradle there are no resources here:
```
 Enumeration<URL> resources = classLoader.getResources(path);
            while (resources.hasMoreElements()) 
```
`resources.hasMoreElements()` returns false although there are cucumber jars (but jetified) in that enumeration

**Comment by mpkorstanje** [comment]
What does a jetified jar look like?

**Comment by lsuski** [comment]
It looks like normal jar but its classes are 'jetified' - all Java6 incompatible language features in bytecode are replaced with Java6 equivalents

**Comment by lsuski** [comment]
When I'm debuging it everything looks ok but for some reason `resources.hasMoreElements()` returns false. However loading class `cucumber.runtime.java.JavaBackend` works

**Comment by mpkorstanje** [comment]
Any chance that your debugger is altering the internal state of `Enumeration`? Either because you've written some expressions or something else?

**Comment by lsuski** [comment]
I debug tests from IDE and gradle task. In first case it works, in second one it doesn't so I don't think this could be related to debugger

**Comment by VitaminPSG** [comment]
@mpkorstanje @lsuski  I've updated project to last `cucumber-jvm` it doesn't help. I also created issue in google tracker issue, but guys from Google are not in a hurry to fix bugs, if you have the opportunity, you can add your comments there and put a star to pay attention to the problem.
Link: https://issuetracker.google.com/u/1/issues/125454040

**Comment by mpkorstanje** [comment]
Given the description you've provided I wouldn't expect a fix. There are too many moving parts involved. I think you'll have to break it down to the specific operation that fails.

**Comment by YervandAlexanyan** [comment]
Hi, I have the same problem, and framework need me as soon as possible. because the development process of my application will stopped .

**Comment by mpkorstanje** [comment]
Cucumber is an opensource project. If you need a fix for a specific problem you will have to provide this fix. Or at the very least describe a clear solution so that others may be able to fix this for you.

However given the nature of the problem, I am not sure if this can be fixed on our end. It would appear to be a problem with the way Android jetifies `classLoader.getResources(path)`.

**Comment by mpkorstanje** [comment]
I'm going to close this issue as it isn't something we can fix. There might be the vague possibility that https://github.com/cucumber/cucumber-jvm/issues/1526 provides a solution but I doubt it.

Please feel free to reopen this if you do know a solution.
