### ISSUE TITLE
Enhancement request --retry flag is still not available

### ISSUE THREAD

**Issue by hemanthsridhar** [cucumber/cucumber-jvm#1706]
Currently the cucumber Java CLI does not provide us the --retry option 
Can you guys please integrate it? 
If there's any issue can we have an alternate solution that we can do so that it's almost the same as --retry

**Comment by mpkorstanje** [comment]
From the README.md

> Please bear in mind that this project is almost entirely developed by volunteers. If you do not provide the implementation yourself (or pay someone to do it for you), the bug might never get fixed. If it is a serious bug, other people than you might care enough to provide a fix.

And if you don't mind using only surefire reports:

https://maven.apache.org/surefire/maven-surefire-plugin/examples/rerun-failing-tests.html

**Comment by hemanthsridhar** [comment]
Is there a way to do the same using gradle

**Comment by mpkorstanje** [comment]
No. Gradles JUnit runner implemetation is quite primitive. I don't think it looks below the class level at all.

Anyway there is a good chance that implementing rerun functionality is more work then making your tests stable. Otherwise there would have been a contribution by now.

If you are using a Webdriver look up articles about writing stable tests with that. Otherwise look up articles about making tests stable in general. It's not hard, just a few patterns to follow and habits to break.

**Comment by hemanthsridhar** [comment]
Thank you @mpkorstanje

**Comment by hemanthsridhar** [comment]
@mpkorstanje 
I tried with your suggestion. Migrated to Maven and used the surefire way of rerunning. However now, I will not be able to run scenarios in parallel.
Is there a way to to use --threads from cucumber cli and use the retry option?

**Comment by mpkorstanje** [comment]
Surefire can execute tests in parallel. Look up the threads option.

**Comment by hemanthsridhar** [comment]
@mpkorstanje 
Yes. But it executes feature files in parallel not the scenarios. Is there a way to execute the scenarios of a single feature in parallel.

I am able to do it using cucumber-testng but when I migrate to cucumber-testng immediately the retry feature of the surefire vanishes.

**Comment by mpkorstanje** [comment]
These are unfortunately the constraints of the tools we're working with. I believe TestNG also has a retry mechanism build in. Have you tried to use that?

**Comment by hemanthsridhar** [comment]
@mpkorstanje The IRetryListener doesn't get executed unfortunately.

**Comment by camohub** [comment]
@mpkorstanje I try to use surefire retry feature and it works pretty well. the only problem is, that the result cucumber.json contains only test which has been running as failed rerun. It would be great if Cucumber will be able to join prev cucumber.json with rerun json file. Honestly I am not able to do it. But it should be possible I mean. Test sometimes crashes not because of wrong pattern but because of unexpected issues on the network. 

Thank you.

**Comment by danyflorez** [comment]
Hi, I'd like to have a guidance on how to develop the retry I have the time to work on it and make a PR

**Comment by camohub** [comment]
My idea is the scenario should rerun immediately after it fails. Simple rerun it again. I dont know if is possible to catch JUnit result if it fails first time and replace it with rerurn result.
