### ISSUE TITLE
Deprecate and remove Needle & Weld

### ISSUE THREAD

**Issue by mpkorstanje** [cucumber/cucumber-jvm#1763]
## Summary

Cucumber supports a number of Java EE containers:
 - CDI2
 - DeltaSpike
 - Needle 
 - OpenEJB
 - Weld

While they are relatively low maintenance as modules go it would be good to remove some of the duplicate functionality.

 * Delta Spike currently supports OpenEJB and Weld and can replace both object factory implementations.
 * Needle is closely tied JBoss and can be replaced with DeltaSpike/CDI2 object factory implementations.

@toepi, @rmannibucau, @lbilger, @jangalinski, @FSeidinger, @aaronwalker since you have all contributed to these modules in the past and present:

1. Are the above statements correct?
2. Do you have any strong objections against deprecating these modules?
3. Any thing else?

**Todo**

- [x] v6.x.x Deprecate
- [x] v7.0.0 Remove

**Comment by rmannibucau** [comment]
Hi @mpkorstanje ,

Weld, potentially OpenWebBeans which was not contributed, and CDI2 clearly overlap and I guess only CDI2 should stay since others don't bring anything anymore.
For CDI1, DeltaSpike makes sense IMHO.
OpenEJB does not have a replacement yet - I guess it should converge to EJBContainer instead of internals - which would then support all EE containers with some CDI mix (EJBContainer includes CDI but not the opposite but you can't use EJBContainer to test a pure CDI/Microprofile app since it would add behavior which can make fail your boot or break classpath). Based on EJBContainer I guess all EE containers are supported so I'd say CDI2 and EJBContainer are required, DeltaSpike for a few years for CDI < 2 and we are good.

Does it makes sense even if EJBContainer still needs to be developped?

**Comment by jangalinski** [comment]
Though the above (needle closely tied to jboss) is not completely true, I am fine with deprecating needle support, haven't used it myself for years.

**Comment by aaronwalker** [comment]
Happy for Weld support to be deprecated.
