### ISSUE TITLE
Not able to create a singleton bean in a Hook (Step)class (spring cucumber)

### ISSUE THREAD

**Issue by abhishek8908** [cucumber/cucumber-jvm#1803]
**Describe the bug**
A defined bean is initialized multiple time inside my hook step class, whereas the scope specified is a singleton using spring cucumber

**To Reproduce**
Create a hooks class in the example
https://github.com/abhishek8908/cucumber-spring-example
https://github.com/abhishek8908/cucumber-spring-example/blob/master/src/main/java/abhishek8908/stepdefs/hooks/HookSteps.java

**Expected behavior**
A singleton Bean must be created, whereas its initializing bean multiple times (Please refer the logs)

**Logs**

> Oct 14, 2019 10:22:27 PM cucumber.runtime.java.ObjectFactoryLoader loadSingleObjectFactory
> INFO: Loading ObjectFactory via service loader: io.cucumber.spring.SpringFactory
> Oct 14, 2019 10:22:27 PM cucumber.runtime.java.ObjectFactoryLoader loadSingleObjectFactory
> INFO: Loading ObjectFactory via service loader: io.cucumber.spring.SpringFactory
> Oct 14, 2019 10:22:27 PM cucumber.runtime.java.ObjectFactoryLoader loadSingleObjectFactory
> INFO: Loading ObjectFactory via service loader: io.cucumber.spring.SpringFactory
> Oct 14, 2019 10:22:27 PM cucumber.runtime.java.ObjectFactoryLoader loadSingleObjectFactory
> INFO: Loading ObjectFactory via service loader: io.cucumber.spring.SpringFactory
> Initiating Belly Class
> Initiating Belly Class
> Initiating Belly Class

**Your Environment**
 - Versions 4.8.0
 - Win OS 10
 - Build tool :Apache Maven 3.6.0

**Comment by mpkorstanje** [comment]
The current implementation of `cucumber-spring` creates an application context for each thread. Since there are multiple application context you'll see multiple instances of your singleton bean. So this is working as intended.

There is a design flaw `cucumber-spring` that requires a new application context for each thread. If you look at the implementation of the `SpringFactory` you'll see that the application context is modified (dirtied) by each test. When starting a scenario all step definitions are added to the context, when the scenario stops, they are removed again. This itself is necessary to avoid sharing state between scenarios. As a consequences Cucumber the application context can not be shared between threads.

If you're interested you could look at https://github.com/cucumber/cucumber-jvm/pull/1604 for a potential solution, I currently don't have the time for it.
