### ISSUE TITLE
Add support for classpath scanning/resource loading in nested jars

### ISSUE THREAD

**Issue by schneebuzz** [cucumber/cucumber-jvm#1931]
**Is your feature request related to a problem? Please describe.**
As of now (v5.5.0) resource loading (features, glue) is not supported for nested JARs as they appear in spring applications built with the `spring-boot-maven-plugin` for example. That is a packaged jar inside the spring boot jars `BOOT-INF/lib` directory.
The use case for this is a custom, spring-based test framework that can handle seperate test packages containing glue, features and possibly additional utilities for test execution.

**Describe the solution you'd like**
Support the resource scanning and loading for nested JARs natively in the cucumber core implementation.  
This can possibly be done with the API provided by spring. They already implement scanning/loading of the described package structure. Of course the spring dependency *bomb* must not be added to cucumber-jvm. So the solution could be a new implementation of the loading/scanning or to provide an API that allows dropping in the loader similar to what can already be done with the `Runtime.Builder#withFeatureSupplier(...)`.

**Describe alternatives you've considered**
Combine core API and spring loader-implementation in `cucumber-spring` where the spring dependencies are already present.

**Additional context**
A nice error message is already present in `JarUriFileSystemService#nestedJarEntriesAreUnsupported` where the nested jar case is not further implemented.
I am unsure if the URI-based approach would be best for loading such nested resources. Usually the classpath resource loaders should be able to pick up whatever it is as long as it is on the classpath instead of parsing URIs. How things get on the classpath can then be the responsibility of someone else?

**Comment by mpkorstanje** [comment]
> I am unsure if the URI-based approach would be best for loading such nested resources. Usually the classpath resource loaders should be able to pick up whatever it is as long as it is on the classpath instead of parsing URIs. How things get on the classpath can then be the responsibility of someone else?

The problem is discovering classes and feature files based on a package name. Say we have a package `com.example` then we can get all resource uris for that e.g. `file:path/to/example1.jar!com/example` and `file:path/to/example2.jar!com/example`.  

However at this point, if we want to know what classes there are we have to open these jar files and rifle through their contents. I don't believe there is a better way to do this. 

Now opening jar files isn't a big deal. Esp with the introduction of the `JarFileSystem`. However Spring Boot includes jar files inside their jars. There is currently no support for that. You can't create a `JarFileSystem` inside a `JarFileSystem`.

The logistics of handling a nested jar file are also quite complex. Either write your own implementation that streams the contents of a nested jar file and processing it on the fly (Springs Solution) or you unzip the jar file to a temporary directory to scan it. 

>  Combine core API and spring loader-implementation in cucumber-spring where the spring dependencies are already present.

There may be a misunderstanding here about what `cucumber-spring` is supposed to do. `cucumber-spring` manages the Spring test context. So Spring in Cucumber. However you are talking about running Cucumber inside a spring application. So Cucumber in Spring. These are very different things. 

Now that doesn't mean that we can't make classpath scanning pluggable. However the typical way of doing this, via SPI won't work. This must be part of the `Runtime.Builder` API which is currently only for internal use. So we'd have to fix that up too.
