### ISSUE TITLE
Scenario Outline is not considering as a scenario from testNGCucumberRunner.provideScenarios().

### ISSUE THREAD

**Issue by chandrasekhar11** [cucumber/cucumber-jvm#1933]
<!--

Hi,

  testNGCucumberRunner = new TestNGCucumberRunner(RunCucumberTest.class);
      
  Object[][] scenarios =  testNGCucumberRunner.provideScenarios();

Provide scenarios is not taking the 'Scenario Outline' as scenario from feature File.

I want to get Scenario Outline as a scenario from  testNGCucumberRunner.provideScenarios().

or is there another approach to write custom code to get Scenario Outline from TestNG Runner Class

* Version used:
<dependency>
    <groupId>io.cucumber</groupId>
    <artifactId>cucumber-testng</artifactId>
    <version>5.5.0</version>
</dependency>
* Operating System and version: win 10

**Comment by mpkorstanje** [comment]
That is correct and unfortunately a limitation imposed by TestNG.

**Comment by chandrasekhar11** [comment]
> That is correct and unfortunately a limitation imposed by TestNG.

Any alternative for this by using latest cucumber testng JAR? I want to use Scenario Outline..

**Comment by mpkorstanje** [comment]
You can use scenario outlines in your feature files. The examples in the outline will be compiled into individual scenarios called pickles. These pickles will be executed by TestNG.

You can't use anything else because TestNG requires that each element provided by a data provider can be executed. Scenario Outlines themselves can not be executed.
