### ISSUE TITLE
After hooks ignore order property

### ISSUE THREAD

**Issue by mitasov-ra** [cucumber/cucumber-jvm#1943]
**Describe the bug**
After hooks run in order of declaration, not in specified order

**To Reproduce**

Set up some After hooks with order:
```java
    @After(order = 3)
    public void ccc() {
        System.out.println("ccc");
    }

    @After(order = 2)
    public void bbb() {
        System.out.println("bbb");
    }

    @After(order = 1)
    public void aaa() {
        System.out.println("aaa");
    }
```

**Expected behavior**
Output is:
```
aaa
bbb
ccc
```

**Actual behavior**
Output is:
```
ccc
bbb
aaa
```

**Your Environment**
 - Versions used - 5.6.0
 - Operating System and version - Windows 10 latest
 - Build tool - Gradle

**Comment by mpkorstanje** [comment]
Works as intended. After hooks run in reverse order from before hooks. 

https://github.com/cucumber/cucumber-jvm/blob/master/java/src/main/java/io/cucumber/java/Before.java#L25-L29
```java
    /**
     * @return the order in which this hook should run. Lower numbers are run first.
     * The default order is 10000.
     */
    int order() default 10000;
```


https://github.com/cucumber/cucumber-jvm/blob/master/java/src/main/java/io/cucumber/java/After.java#L25-L29
```java
    /**
     * @return the order in which this hook should run. Higher numbers are run first.
     * The default order is 10000.
     */
    int order() default 10000;
```

**Comment by mitasov-ra** [comment]
Well, it is really bad design, IMHO. 😕
Thanks, Anyway.

**Comment by aslakhellesoy** [comment]
Consider the case where we need to start/stop a server and connect/disconnect a client. It needs to be done in the following order:

- start server
- connect client
- disconnect client
- stop server

With the current design this can be written as follows:

- `Before` start server
- `After` stop server

- `Before` connect client
- `After` disconnect client

Note how related hooks are grouped. I personally find code easier to navigate when related things are grouped. You're arguing for this:

- `Before` start server
- `Before` connect client

- `After` disconnect client
- `After` stop server

I find this harder to reason about because related concepts are now far away from each other.

**Comment by mitasov-ra** [comment]
Good example, now I see the true reason for that.
But semantically there is implicit behavior, because when I'm reading "order" I assume that order is ascending, as it is default behavior for all "order"s.
So, obviously, the best solution would be using "reverseOrder" name for that property.
