### ISSUE TITLE
Spring components are shareable between test threads when tests have been started in the parallel mode.

### ISSUE THREAD

**Issue by dabogee** [cucumber/cucumber-jvm#1949]
**Describe the bug**
Spring components are shareable between test threads when tests have been started in the parallel mode. When a spring component has been modified in a scenario which runs, for example, in **thread-1** then this changes are going available in another **thread-2** for totally different scenario.

**To Reproduce**
Clone the following project [com.dabogee.cucumber.v5.6.0-spring-issue](https://github.com/dabogee/com.dabogee.cucumber.v5.6.0-spring-issue) and run tests using `mvn clean test -Pv5.6.0`

**Expected behavior**
Should complete without any failures. Execute `mvn clean test -Pv4.7.2` for expected behavior.

**Context & Motivation**
Unable to run test suites in parallel mode.

**Screenshots**

**Your Environment**
 - cucumber-jvm 5.5.0, 5.6.0

**Additional context**

**Comment by mpkorstanje** [comment]
This is intentional. Please refer to:

* https://github.com/cucumber/cucumber-jvm/blob/master/release-notes/v5.0.0.md#sharing-the-spring-application-context
* https://github.com/cucumber/cucumber-jvm/blob/master/CHANGELOG.md#changed-4

And without looking too in depth at your reproducer I suspect that you'll want to annotate your `ProductComponent` with `@Scope(CucumberTestContext.SCOPE_CUCUMBER_GLUE)`. For more information please refer to:

https://github.com/cucumber/cucumber-jvm/tree/master/spring#sharing-state-between-steps

**Comment by dabogee** [comment]
Hi, @mpkorstanje ! thanks, that's work
