### ISSUE TITLE
Spring Bean objects for the completed scenarios are not getting Garbage collected in Cucumber version 5 and above

### ISSUE THREAD

**Issue by mmanikandan88** [cucumber/cucumber-jvm#2066]
**Describe the bug**
Spring Bean objects for the completed scenarios are not getting Garbage collected in Cucumber version 5 and above

Prerequisites – Need VisualVM(freeware)/any other profiling tools to be installed to see the memory profiling.
1. Go to Cucumber4 project
2. Run the RunCukesTest class with TestNG configuration by passing JVM arguments as -Ddataproviderthreadcount=2
3. While application running, switch to the VisualVM and on the Application panel, double click on the PID 
4. Go to the profiler tab and click on the Memory settings
5.Enter com.test.** in the Profile classes
6. Click on the memory button to start profiling.
7. You can observe whenever GC is happening all the Beans for the completed scenarios are getting garbage collected and the generations will never cross more than 2.

8. Now repeat the steps from 1 to 6 with Cucumber5 project. Only version upgraded and few methods related to version 5 updated
9. You can see Beans generation will keep increasing as the scenarios getting passed after many GC happened. They are not getting garbage collected.This will lead to Out of Memory error after running 1000 tests

**Expected behavior**
Spring Beans for the completed scenarios should get GC as it is happening in Cucumber version 4.8.0

**Context & Motivation**
We have lot of Autowired utility class and close to ~2500 test scenarios. Those Autowired beans occupying heap and not getting GC and we are running to out of memory problem after crossing 1000 scenarios....
We are trying to keep upgraded to latest version to use the new features.

**Screenshots**
Cucumber -4 
Visual VM – After Few scenarios passed 
![image](https://user-images.githubusercontent.com/20919551/88329666-50eebb80-ccf8-11ea-830a-85b339ae6ed8.png)

Cucumber -5
Visual VM – After Few scenarios passed
![image](https://user-images.githubusercontent.com/20919551/88329721-67951280-ccf8-11ea-85ff-31b114f241ff.png)

**Your Environment**
- Versions used  Cucumber 4.8.0 and Cucumber 5.6.0
 - Operating System and version : Mac  Mojave
 - Build tool [Apache Maven 3.5.4]

[cucumber4.zip](https://github.com/cucumber/cucumber-jvm/files/4968338/cucumber4.zip)
[cucumber5.zip](https://github.com/cucumber/cucumber-jvm/files/4968340/cucumber5.zip)

**Comment by mpkorstanje** [comment]
Heya, thanks for reporting this!

When I'm looking at your reproducers there is quite a bit going on. This makes it rather hard to see what might be the root cause. For example do you need everything in the `@CuucmberOptions`,the  `parallel = true`, multiple actions, ect to reproduce the problem? Could you help out a bit by removing everything that isn't strictly needed to reproduce the problem? 

Would you also be able to provide a reference chain through which the beans are being kept alive?

And unfortunately your screen shots have shrunk to the point of being illegible. Would you be able to provide new ones?

**Comment by mpkorstanje** [comment]
Ah. Nevermind. Think I found it.

**Comment by mpkorstanje** [comment]
So this is caused by using a combination of:

- Using `cucumber-java8`
- Using the `plugin = "json"` (or any other plugin that implements `EventListener`)
- TestNG or when not using TestNG executing scenarios in parallel.

Removing any of these factors should prevent the memory leak.

The root cause seems to be that  `io.cucumber.java8.AbstractGlueDefinition` retains a reference to the step definition classes. In turn glue definitions are used in events, which is are in turn stored until the end of the test when scenarios are executed in parallel to facilitate formatters that can not handle concurrent events.

**Comment by mmanikandan88** [comment]
My Apologies for not replying soon. Thank you ... 🙏 .You are awesome. So it looks like your changes got merged. Which cucumber version do I need to use in our project?

###

**Comment by mpkorstanje** [comment]
That would be v6.3.0. Check the change log for more information.
