### ISSUE TITLE
Cucumber to execute the scenarios in a particular order

### ISSUE THREAD

**Issue by dipakbachhav** [cucumber/cucumber-jvm#2214]
How we can assign priority to execute the cucumber scenarios in a specific order?

I need 1 to be compulsorily executed before 2, and 2 to be compulsorily executed before 3, and so on. Is there a way to force Cucumber to run the scenarios in the order in which they are present in the feature file?

```
@Scenario_1
@labelA
Given....

@Scenario_2
@labelB
Given....

@Scenario_3
@labelA
Given....

@Scenario_4
@labelA
Given...

@Scenario_5
@labelB
Given...
```

**Comment by mpkorstanje** [comment]
Scenarios are supposed to be independent units. If you have scenarios that depend on each other consider rewriting them so that they are independent again. In practice Cucumber does execute feature files in lexical order file name order and within a feature file scenarios are executed from top to bottom. However you should not depend on this.
