### ISSUE TITLE
@Given & @When with same regexp results in error

### ISSUE THREAD

**Issue by hutchy2570** [cucumber/cucumber-jvm#223]
When I have a @Given and a @When step definition with the same regexp I get a duplicate step definition error.

---

Example with 1.0.0-RC16:

Scenario: Test duplicate steps
    Given I do something
    When I do something

```
@Given("^I do something$")
public void givenIDoSomething() {
    //Do something
}

@When("^I do something$")
public void whenIDoSomething() {
    //Do something
}
```

Gives the result:

Exception in thread "main" cucumber.runtime.DuplicateStepDefinitionException: Duplicate step definitions in Steps.givenIDoSomething() and Steps.whenIDoSomething()

---

These step definitions should be treated as different due to the @Given & @When annotations, but they are not.

**Comment by gulhe** [comment]
This feature makes no sense on the basis of what cucumber is for.
Cucumber is supposed to bring test-definitions closer to how one would express them.

If not being able to distinguish between two different sentences (beacause ... changing the adverbs you change the meaning) **"is"** a feature then that feature is ill-designed or the concept is flawed.

**Comment by aslakhellesoy** [comment]
@gulhe @hutchy2570 can you give me a concrete, real world example of two steps with identical text (but different keyword)?

**Comment by gulhe** [comment]
`Given` I have 5 cucumbers
`When` I have 5 cucumbers
`Then` I have 5 cucumbers

 - The first one sets the system so that it's representation of my possessions includes 5 cucumbers
 - The second polls the system until my represented possessions include 5 cucumbers
 - The last one `assertThat(myPossessions.cucumbers.size()).is.equalTo(5)`

Same would go for any type of state (`browser.currentLocation`, `credential`, `application.status`, ...).

Adverbs inherently impact the meaning of the sentence they are in. That is their purpose.

That is a fact in english that can be even more striking in other languages.

**Comment by aslakhellesoy** [comment]
I think that’s a contrived example, not a real world one, but I’ll go with that.

Words matter. A Given describes a *context* - or a state. A When describes an *action*. “I have 5 cucumbers” is not an action. A Then describes an *expectation*. You could argue that “I have 5 cucumbers” is an expectation, but it is a poorly worded one.

This could (and should) be reworded to remove ambiguity and make it more explicit:

```gherkin
Given I have 5 cucumbers
When I buy 4 cucumbers
Then I should have 9 cucumbers
```

When you put effort into distinguishing how you express state, actions and expectations, your domain language is no longer ambiguous, and the feature you’re asking for is not needed.

Cucumber is an opinionated tool. That’s why it doesn’t let you mix things up like this. You can read more about this in @lunivore’s excellent blog post [a little tense](https://www.google.co.uk/amp/s/lizkeogh.com/2014/09/02/a-little-tense/amp/).
