### ISSUE TITLE
Cucumber JUnit 5 Change of behaviour: Cannot have multiple spring boot cucumber contexts

### ISSUE THREAD

**Issue by davidmelia** [cucumber/cucumber-jvm#2230]
**Describe the bug**
Cucumber Spring via JUnit 5 should auto default the glue path to the path of the running test otherwise this means you cannot have multiple spring contexts in the same project.

**To Reproduce**
https://github.com/davidmelia/cucumber-spring-junit5 contains an example.  I have two JUnit 4 tests
CucumberJunit4Test1Test and CucumberJunit4Test2Test with their own spring glue which works fine where  io.cucumber.java.JavaBackend picks the glue path [classpath:/com/melia/junit4/test1] and [classpath:/com/melia/junit4/test2] respectively.  So far so good.

I also have two JUnit 5 tests CucumberJunit5Test1Test and CucumberJunit5Test2Test but they both default to the glue path [classpath:/] where I get the error

```
SEVERE: Unable to start Cucumber
io.cucumber.core.backend.CucumberBackendException: Glue class class com.melia.junit5.test2.CucumberJunit5Test2Steps and class com.melia.junit5.test1.CucumberJunit5Test1Steps are both annotated with @CucumberContextConfiguration.
Please ensure only one class configures the spring context
	at io.cucumber.spring.SpringFactory.checkOnlyOneClassHasCucumberContextConfiguration(SpringFactory.java:92)
	at io.cucumber.spring.SpringFactory.addClass(SpringFactory.java:65)
	at io.cucumber.java.JavaBackend.lambda$loadGlue$1(JavaBackend.java:41) 

```

**Expected behavior**
I would expect Cucumber JUnit 5 to default the glue path to the directory of the running test otherwise we cannot have multiple spring contexts in the same project which make migration impossible.

**Comment by mpkorstanje** [comment]
Feature files don't have to be on the class path so that wouldn't work as an assumption. They may also not follow the same organization structure and the spring configurations would. So I don't see any solution here.

With JUnit4 this would be solved by using different Runners, each with their own glue and feature configuration. However the Junit 4 Runners combined were both suites and test executors. These concepts got split with Junit 5. Currently to run different suites you have to use the Junit Platform Launcher API.  

This is less then ideal so I'm currently waiting for https://github.com/junit-team/junit5/pull/2416 to be merged to provide a programmatic way to execute suites.

**Comment by davidmelia** [comment]
@mpkorstanje now the above junit PR has been merged can you give me pointers how I can solve this issue?

Thanks

**Comment by mpkorstanje** [comment]
You'd annotate two classes with `@CucumberContextConfiguration` in different packages. Then you'd define two suits using the cucumber engine with different values for `cucumber.glue` property and different test selectors. Each one targeting a different set of features + glue.
