### ISSUE TITLE
Option do define feature order without workaround

### ISSUE THREAD

**Issue by punkratz312** [cucumber/cucumber-jvm#2297]
please add the possibility to define hard coded execution oder as last workaround. its not hard to implement and wont break general approach that tests need to be independent 💯 right.

As always there might be an exception in case of an initial password change its mandatory that the update password scenario runs first. As otherwise all the other tests would need to deal with this situation too and thats not practicable.

Please implement the feature options they are interpreted all over the internet even tho it has not any effect at all, to define multiple feature blocks. Still the ugly number_prefix workaround must be used to workaround this special case...

Desired solution: 

![image](https://user-images.githubusercontent.com/8830888/117272674-b3fea880-ae5b-11eb-92c6-6d2e0b0ad54b.png)

Actual workaround:

![image](https://user-images.githubusercontent.com/8830888/117273272-469f4780-ae5c-11eb-8bd2-9c71bbf8b33f.png)

https://forum.katalon.com/t/how-to-run-multiple-feature-files-in-a-specific-sequence-using-cucumber-runner-class/24327

**Comment by mpkorstanje** [comment]
Given that @punkratz312 is using [cucumber-serenity](https://github.com/serenity-bdd/serenity-cucumber) rather then `cucumber-jvm` I reckon this request is addressed to the wrong project.

I also don't think this feature is desirable. It will be rather complicated and counter-intuitive to explain and document how this order will be resolved. For example:

```
com/example/feature-001.feature
com/example/ #contains features 01-999
com/example/feature-099.feature
```

This creates the suggestion that feature 001 should go first and feature 099 last, and all other features 002-098, 100-999 in between. But because is 099 part of `com/example/` is clearly shouldn't go last.


Finally the use case for this feature also isn't something we're looking to support. The assumption is that scenarios are independent. The typical solution to the problem is to create a new account for each scenario -- preferably through an API to speed things up. When real world resources are involved it is not always possible to make scenarios truly independent but the complexity of dealing with that should be dealt with by the user rather then framework.

One approach here would be to bring the account in a usable state once before it is used.

```java
static boolean passwordReset = false;


@Before
public void resetPassword(){
  if(passwordReset){
   return;
  }
  // reset password here
  
  passwordReset = true;
}
```

**Comment by punkratz312** [comment]
Thanks for the suggestion I will give it a try
