### ISSUE TITLE
how to config feature with different path ？

### ISSUE THREAD

**Issue by ahu0605** [cucumber/cucumber-jvm#2360]
**Is your feature request related to a problem? Please describe.**
when I use junit5 ,I can not set different path .feature  eg: src/test/xxx/xxx.java ,src/test/resources/xxx/xx.feature

**Describe the solution you'd like**
I want to config freedom path for .feature

**Comment by mpkorstanje** [comment]
I have a very hard time understanding what your problem is. So I'm going to guess a few answers:

1. When using the `@Cucumber` annotation, Cucumber will look for features in the same package as the annotated class. When using the the  `@Cucumber` there can only be one value of `cucumber.glue`.

2. You can use the [supported discovery selectors](https://github.com/cucumber/cucumber-jvm/tree/main/junit-platform-engine#supported-discovery-selectors-and-filters) from JUnit 5. You can use these through the [JUnit Platform Launcher API](https://junit.org/junit5/docs/current/user-guide/#advanced-topics) or through their [Console Launcher](https://junit.org/junit5/docs/current/user-guide/#running-tests-console-launcher).

3. Finally, if you have multiple suites, each with a different set of features and glue, you can use the experimental `junit-platform-suite` to declare multiple suites, each with different configuration parameters. https://github.com/mpkorstanje/junit-platform-suite-demo

If this doesn't help, perhaps you can provide a concrete example of your problem.

**Comment by ahu0605** [comment]
thank you，I will try
