### ISSUE TITLE
Please create any installer or add a linux binary to the Arch user repository.

### ISSUE THREAD

**Issue by kevincrans** [cucumber/cucumber-jvm#2417]
**Is your feature request related to a problem? Please describe.**
I'm frustrated when I can't find the Linux app I want in the Arch Linux AUR, nor a binary anywhere on the web, or when I don't know for which platform something is, or if something is proprietary or has a copyleft license, which is why I wanna try Cucumber. 

**Describe the solution you'd like**
I'd like to directly install it using the AUR tools I have, or download a msi installer for Windows.
In the pacman AUR, it should also serve as a substitute for other java vm's.

**Describe alternatives you've considered**
Giving feedback instead of hours of searching and giving up.

**Additional context**
I'm planning to move away from OpenJ9 and OpenJDK.

**Comment by aslakhellesoy** [comment]
Although Cucumber-JVM has a [command-line interface](https://github.com/cucumber/cucumber-jvm/blob/main/core/src/main/java/io/cucumber/core/cli/Main.java) that can be run with `java -jar cucumber-core.jar`, it is not usable on its own.

Cucumber-JVM is also a Java library with classes that you have to reference from step definitions. This requires using a build tool like Maven or Gradle to:

1. Download the Cucumber jar files
2. Invoke `javac` with the right `-classpath` arguments to build your code
3. Invoke `java` to run Cucumber (typically via JUnit rather than the command-line interface)

Cucumber-JVM just isn't a standalone command-line tool that it makes sense to install with a package manager. It's a Java library that you'd install and run with your Java build tool.

So this request doesn't make much sense to me.

If you were able to install it with a linux package manager, how would you actually use it once it's installed?

**Comment by mpkorstanje** [comment]
> I'm planning to move away from OpenJ9 and OpenJDK.

@aslakhellesoy 
This leads me to believe that @kevincrans believes that Cucumber is a JVM implementation like OpenJDK, Azul, Oracle, ect.

**Comment by aslakhellesoy** [comment]
@kevincrans Cucumber-JVM is a test automation tool that runs on any JVM.
