### ISSUE TITLE
JUnit5 test execution shows rest of the tests as ignored

### ISSUE THREAD

**Issue by kakliniew** [cucumber/cucumber-jvm#2922]
### 👓 What did you see?

I did an upgrade from junit4 to junit5. After this change, when I run the tests as before (intelijj run configuration using `-Dcucumber.filter.tags=@test`), it runs these tests for me, but shows all other detected tests as ‘ignored’. They are also included in the report. Is it possible to make them not be taken into account at all if they do not meet the cucumber.filter.tags condition?

This is how I specify acceptance test runner:
```
@Suite
@IncludeEngines("cucumber")
@SelectClasspathResource("/features")
public class AcceptanceTestSuite {}
```

And the result is like: `Tests failed: 1, ignored 520 of 521 tests`

### ✅ What did you expect to see?

Result to show only executed tests not ignored

### 📦 Which tool/library version are you using?

junit5JupiterVersion='5.11.0-RC1'
junit5PlatformVersion='1.11.0-RC1'
cucumber='7.15.0'

### 🔬 How could we reproduce it?

cucumber + junit5 base project and use intelijj idea run configuration for junit
specify -Dcucumber.filter.tags=@tests as VM options

### 📚 Any additional context?

Is this specific to junit5 or can it be solved somehow? I've tried various options, but none helped.

**Comment by mpkorstanje** [comment]
As you are using JUnits Suite Engine to run Cucumber you can use the `@IncludeTags` and `@ExcludeTags` annotations. These will properly remove scenarios instead of skipping them.

https://junit.org/junit5/docs/current/api/org.junit.platform.suite.api/org/junit/platform/suite/api/package-summary.html

These do take JUnit tag expressions. There is a small mapping between these.

https://github.com/cucumber/cucumber-jvm/tree/main/cucumber-junit-platform-engine#tags

I'm not sure IDEA supports JUnits tag expressions, if not you may want to file a feature request.

**Comment by aniketmankar** [comment]
@kakliniew I faced the same problem

Use -Dgroups=tagName or -D"groups=tagName1,tagName2" (for multiple tags) instead of -Dcucumber.filter.tags

**Comment by kakliniew** [comment]
@mpkorstanje using `@IncludeTags` and `@ExcludeTags` works fine, but it is unfortunately hardcoded. 
There is an option to run "Tags" in intelijj Idea run configuration, but then for some reason it runs the test [twice.](https://intellij-support.jetbrains.com/hc/en-us/community/posts/115000437084-Idea-running-JUnit5-tests-twice) 
I dont get it why. First run is as "default package" and the second as my `AcceptanceTestSuite`.

@aniketmankar Unfortunately this has no effect when I add to the VM options in the run configuration. I guess it works with maven-surefire-plugin but I use gradle/junit run config in intelijj idea

I have tried different ways, but unfortunately have not found a working solution. 
The added ```useJunitPlatform{ includeTags ‘test’ }``` works if I run the tests as gradle, but here I run it as junit and specify the  `AcceptanceTestSuite` class as the entry point

**Comment by mpkorstanje** [comment]
> There is an option to run "Tags" in intelijj Idea run configuration, but then for some reason it runs the test [twice.](https://intellij-support.jetbrains.com/hc/en-us/community/posts/115000437084-Idea-running-JUnit5-tests-twice)

Sounds like you'd have to create a feature request with IDEA. The tags filter is orthogal to the test selectors (class, file, package, ect) in JUnit 5. So you should be able to select a class, package, ect and also use a tag filter at the same time.

> I dont get it why. First run is as "default package" and the second as my AcceptanceTestSuite.

In JUnit 5, aside from Jupiter and Vintage there can be many test engines. For example Cucumber. 

But IDEA has rather limited support for JUnit 5. It looks like they recycled what they had for JUnit 4 and made that work with 5. 

So IDEA can only select classes and not feature files with JUnit 5. So as a work around we use the Suite Engine to run the Cucumber Engine.

Except when you use the "Tags" option. Then IDEA will select all tests in a package. The Cucumber Engine understands that request and selects all the tests in that package. But then because the Suite Engine is also used, this will also discover tests. So tests are discovered twice.

You could work around this by moving your features from `src/test/resources/com/example/features` to `features` in the root of your project or any other directory. The use the directory selector in the runner class to select the features.

**Comment by aniketmankar** [comment]
@kakliniew I use IntelliJ Idea as well for developing Cucumber-JUnit tests, but yes, you are right - I am using maven instead of gradle. You could try shifting to maven and using the surefire plugin if it is not a concern.

**Comment by mpkorstanje** [comment]
Pff. That is kinda sad. Best you can do then is use the workaround I mentioned above - move your features from the classpath to a regular project folder.

**Comment by kakliniew** [comment]
@mpkorstanje I will think what to do about it. Your answers as usual were very helpful, thank you!

Closing, the problem is not with cucumber-jvm, but with Intelijj IDEA. 

I am wondering how maven-surefire solves this problem. I need to do some reading on this

**Comment by mpkorstanje** [comment]
> I am wondering how maven-surefire solves this problem. I need to do some reading on this

They don't. Their current implementation just doesn't cause the problems that IDEAs implementation does.

Surefire scans for classes named "Test". Then creates a discovery selector for each class found this way. The Cucumber engine doesn't resolve any classes, so nothing happens. But the Suite Engine can discover these. So when the runner class is inspected, the Suite Engine will use the JUnit Platform API to resolve the `@ClasspathResource` annotation which can be resolved by the Cucumber Engine.

And then the tag filter is applied. 

While Cucumber was invoked twice, no tests were discovered in the first attempt (unlike IDEA which uses the package selector, which Cucumber can resolve).
