### ISSUE TITLE
[Cucumber-JVM] Extracting Scenario Info before executing the Scenario

### ISSUE THREAD

**Issue by yaggarwal** [cucumber/cucumber-jvm#368]
Currently the Before hook also accepts an argument of ScenarioResult which is not very useful. This is rather indeed useful in After hook , after the scenario has finished executing.

Before executing the scenario we should be able to fetch the scenario info like Scenario name, tags etc. One example can be below:

String CurrentMarket;
@before
public void executehook(Scenario sc){

```
System.out.print("Inside Before Hook");

List<Tag> tags = sc.getTags();
if(tags!=null){

    CurrentMarket = tags.get(0).toString();
}
```

**Comment by cdewangan** [comment]
Happy New Year to you all!!!

I was looking for tag info (of scenario and feature) before executing scenario because:

I wanted to run my scenario on particular mobile device based on tag provide(i.e. if the tag is ios I could run on ios devices, if its android I can launch android runner ) , before starting the test (scenario) I need to launch my runner from Before, based on tags.

Please let me know if anyone have solution for this issue?

Thanks in advance,

**Comment by aslakhellesoy** [comment]
@cdewangan please ask questions in the [support](https://cucumber.io/support) forums.

This is a 3 year old closed issue, not a good place to have a discussion or ask for help.
