### ISSUE TITLE
JUnit Rule annotation is not supported

### ISSUE THREAD

**Issue by rlogiacco** [cucumber/cucumber-jvm#393]
The JUnit Rule annotation support would be very useful to allow to take snapshots on failing tests, but the Cucumber JUnit runner does not support such annotation.
I think that it should be easy to add this support by modifying the runners and introducing the JUnit Statement class usage: I've forked the project and started working on it: please let me know if this is an unwanted feature.

**Comment by markwinspear** [comment]
Hi. I came across this thread because I am trying to put together a simple framework using a Page Object Model patten using Webdriver and using Cucumber as the BDD framework. I'm not a developer first and foremost, however I have taken the advice of Dave Haeffner in his book 'Selenium Guidebook for Java' in setting up a Base test class which uses JUnit's rule to set up an external resource and set capabilities then fire up a browser either locally or in saucelabs.

I have conflict between this and my cucumber annotations and cannot get the two to play nicely together when my base test class is extended by my SearchTestDefinitions class.  I suspect that if the cucumber api supported JUnit rule, I would not get this issue (but as I say, I am not a developer by nature). 

Any advice on how to combine the two if possible would be welcomed

The code is at https://github.com/markwinspear/SeleniumCucumberJavaBasicTest2

Many thanks
Mark

**Comment by mikeholler** [comment]
Rules are important for Android. See #894.

**Comment by johndeverall** [comment]
I just came across this thread - see Serenity issue https://github.com/serenity-bdd/serenity-core/issues/221

It seems this feature would be very helpful for Spring integration, and a lot of people use Spring in the JVM world. Is there any chance this could be looked at again?

**Comment by alb-i986** [comment]
+1

I think the solution would be to have `cucumber.api.junit.Cucumber` extend `BlockJUnit4ClassRunner` instead of `ParentRunner`. In fact, BlockJUnit4ClassRunner encapsulates the Rules handling logic.
I'll see if I can find some time working on it.

**Comment by johndeverall** [comment]
I'm also wanting to put some time into this but haven't looked into it since I last commented as I've been away on holiday. @alb-i986 I'll take a look at what you're suggesting. It sounds like you're ahead of me in conceptualizing a solution. I'll be able to comment more once I take a fresh look at the code.

**Comment by alb-i986** [comment]
@aslakhellesoy 
Would you agree on having `cucumber.api.junit.Cucumber` extend `BlockJUnit4ClassRunner` instead of `ParentRunner`? Can you foresee any issues in doing that?
Thanks

**Comment by JasonSmiley208** [comment]
I can think of one potential issue, but maybe not an issue (not sure how Cucumber.class is being used).

`BlockJUnit4ClassRunner` does not work with dependency injection frameworks like Spring. There is Spring JUnit Runner for example and I am assuming other Dependency Injection Frameworks (DIs) use their own runners as well. I know that the Spring Runner current does not support all @Rule annotations (in the documentation).

Therefore, if `cucumber.api.junit.Cucumber` is not the same runner which is used for DI Runner implementations, then I see no potential issue updating the runner (with my limited knowledge). 

If this class is being used for by the DI cucumber runners, then you might just need a "CucumberJunitRule" runner for Pure Java implementations.

**Comment by rlogiacco** [comment]
There is also a JUnit 5 alternative... :)

Il lunedì 29 febbraio 2016, Jason Smiley <notifications@github.com> ha
scritto:
