### ISSUE TITLE
Report server for receiving results over HTTP 

### ISSUE THREAD

**Issue by aslakhellesoy** [cucumber/cucumber-jvm#552]
Say we want to generate a JSON or HTML report from Cucumber running on Android. How do we get the report out of Android and onto another machine?

HTTP PUT.

The bulk of this is already implemented in [URLOutputStream](https://github.com/cucumber/cucumber-jvm/blob/master/core/src/main/java/cucumber/runtime/io/URLOutputStream.java)

What we need is a simple web server that can listen for the incoming files and write them to disk.

We also need to make sure we can say `--format html:http://some.host/report`

**Comment by SierraGolf** [comment]
@aslakhellesoy I think implementing a web server of which the behaviour is yet completely undefined is overkill. Being able to just retrieve any format (html, json, junit) after the test run from the device is a lot simpler and can be achieved easily with any build system (ant, maven, gradle) by just running ```adb pull filepath```

do you still believe this is viable approach? I don't see any one from the community requesting this feature.

**Comment by aslakhellesoy** [comment]
I wonder if the easiest would be to implement the Cucumber [wire protocol](https://github.com/cucumber/cucumber/wiki/Wire-Protocol) in Cucumber-JVM. This would mean only a small subset of Cucumber-JVM would run on the device while the rest of it would run on a host machine. The wire protocol would send all the results back to the host.

WDYT?

**Comment by SierraGolf** [comment]
*disclaimer: I am absolutely unfamiliar with the wire protocol so please correct me if I make wrong assumptions*

If I understand the wire protocol correctly, it is implemented in such a way that the executor establishes a connection to a remote system (e.g. an android device) and communicate with it (ask for steps, tell to execute steps).

Afaik this is not possible with android. An android application/instrumentation can not open a port on the devices and listen for incoming requests. One would need to inverse the flow, like calabash does it.

I think the wire protocol would need to be extended so that the executor (host system) listens on a specified port for potential test participants to register.

As soon as everyone is registered the executor would start orchestrating tests across the participants.

The more I think about it the more I like the approach. The wire protocol increases the interoperability of cucumber exponentially.

**Comment by aslakhellesoy** [comment]
@SierraGolf I wasn't aware that Android couldn't listen for incoming connections. Inverting the flow should be relatively easy though.

Yeah, I just think having a smaller amount of code running on the device would be beneficial in many ways.

Aslak

**Comment by SierraGolf** [comment]
@aslakhellesoy I think I have to revoke my previous statement. it is probably possible to create such a socket connection from android.

Anyhow, I have a few other things on my list before I can start thinking more about adding wire protocol support to cucumber-jvm, but I find the idea fascinating and I think there is great potential.

**Comment by brasmusson** [comment]
One you get out of the box know that cucumber-android executes the same way as any other Android Instrumentation test, is the integration with IDE's/build-system. In your IDE, you right-click select "run as Android test" the the code is compiled, uploaded and the features executed, with (at least rudimentary) notifications back to the IDE.
I guess that it would require something extra to start both a host server and the device executor from a "run as" menu in an IDE, so maybe using the wire protocol to execute on Android will not be so much a replacement for the current cucumber-android, as a complementing alternative?

**Comment by SierraGolf** [comment]
@brasmusson I see it also more as an alternative for exactly the reasons you mentioned.

What I am more excited about is that you can easily setup complex scenarios using different systems like a rest-api, an android-application and a web-application.
