### ISSUE TITLE
build failure under window with featureWithOutlineTest(cucumber.runtime.formatter.JSONPrettyFormatterTest)

### ISSUE THREAD

**Issue by MengJueM** [cucumber/cucumber-jvm#559]
1) just checkout the latest cucumber-jvm
2) run mvn clean install per the guide in Wiki
3) got below error:

https://gist.github.com/mengjuesh/6031320

**Comment by lunivore** [comment]
Hi @MengJueM, I notice that this report is now pretty old, and the codebase has moved on significantly. Is this error still important to you? If so, please could you resubmit your errors as the old pages are now missing, or let us know that you're working on that? Otherwise I will close this ticket in a week.

**Comment by MengJueM** [comment]
@lunivore Please close this issue. The codebase is changed greatly and this is not so necessary to verify again.
