### ISSUE TITLE
Spring wired dependencies seem to produce race conditions in Cucumber tests

### ISSUE THREAD

**Issue by reynoldsm88** [cucumber/cucumber-jvm#645]
We have a very large test suite with 100+ scenarios. Every once and awhile this results in race conditions where it appears that the @Before tagged method is run before another scenario is finished running.

Basically, we maintain test repositories that behave like our real ones but are only used for testing and we use data tables to populate the repositories. These are wired in with spring, and most of our scenarios use these repository implementations. We are seeing intermittent failures and it appears to be that our cleanup method (implemented as a cucumber @Before that clears the old data out of the repos) runs before the assertion steps in an @Then step definition finishes running. Is this a known problem? Also, any insight into best practices regarding Cucumber based testing are welcome, as it might influence a refactoring effort in our test plan.

Again, we believe this is the result of race conditions because it only happens to certain scenarios and only once and awhile. It occurs both locally on developer machines as well as on our CI server. Any insight is appreciated.

**Comment by mpkorstanje** [comment]
Looking at the code I can see no probable cause for this in cuucmber-jvm. The entire framework is single threaded. Steps may however timeout when they take to long. If steps spawned any new threads these may continue to run. This could cause the behavior you are seeing.

That said the codebase has changed significantly since 2013. If you are still experiencing this issue please reopen this issue.
