### ISSUE TITLE
Test fails : HTMLFormatterTest#writes_valid_report_js

### ISSUE THREAD

**Issue by yoelb** [cucumber/cucumber-jvm#729]
If host JVM Locale is different of en or us, this test fail.
It seemes that Locale is initialised without parameter provided in parent pom cucumber-jvm.xml:  
         <plugin>
                    <groupId>org.apache.maven.plugins</groupId>
                    <artifactId>maven-surefire-plugin</artifactId>
                    <version>2.17</version>
                    <configuration>
                        <argLine>-Duser.language=en</argLine>
                        <argLine>-Xmx1024m</argLine>
                        <argLine>-XX:MaxPermSize=256m</argLine>
                        <argLine>-Dfile.encoding=UTF-8</argLine>
                        <useFile>false</useFile>  
                    </configuration>
                </plugin>

A dirty workaround is to redefine  <argLine>-Duser.language=en</argLine> in cucumber-core.xml.

If someone has an better and elegant solution, please submit it.

**Comment by mpkorstanje** [comment]
@mlvandijk I'm guessing we're not passing a locale properly somewhere. But this issue is rather old. The first step should be reproducing it.

**Comment by mlvandijk** [comment]
## Root cause:
The test fails because the expected error message is in English. If Locale is set to different language (using Locale.setDefault()), the actual error message is in the language set as default.

## Steps to reproduce:
Version: Current master branch (commit a6dff1d)

Set a different Locale at the beginning of the test, for instance:
` Locale.setDefault(new Locale("fr", "FR"));`

Expected: Error message starts with: "ReferenceError: \"document\" is not defined."
Actual error message starts with: "ReferenceError: "document" n'est pas défini" (i.e. in French, not English)

Sidenote: I could not reproduce this by setting Language to Dutch on OS X and restarting (which I expect would have worked on Windows)

## Possible solutions:
1. Set Locale to new Locale("en", "US") explicitly at the start of this test. 
> After you set the default locale with this method, subsequent calls to Locale.getDefault() will return the newly set locale. (http://www.oracle.com/technetwork/articles/javase/locale-140624.html#using)

It could be reset to the original Locale using a finally block, which is expected to always run.
Creating PR for this solution to illustrate; if OK then this solution can be used.

2. An easier solution might be to limit the check on expected error message to check for startsWith(""ReferenceError: \"document\""), but I'm not sure if the test would then still have the same value.

**Comment by mpkorstanje** [comment]
I'm not impressed by a test that throws a reference error and because of that considers a piece code to be valid. I reckon it would be best to compare the `report.js` against an oracle. The actual script shouldn't be to long to put entirely in the test.

**Comment by mlvandijk** [comment]
@mpkorstanje So, option 3 something I haven't thought of: improve the value of the test by checking that the report contains the data from the db.
This would (should) also be a Locale independent test, fixing the original problem.

I'll close the PR and give it a try.

**Comment by mlvandijk** [comment]
I've added a test that checks for a piece of valid js, not sure if this adds a lot of value as several other tests also check for specific pieces.
Still trying to figure out where it gets the Locale and hiw to override that during build/unit tests, so as not to mess with individual users Locale settings...

**Comment by mpkorstanje** [comment]
The Locale was used by the Javascript interpreter.

**Comment by mlvandijk** [comment]
@mpkorstanje Since you are writing 'was'; are you implying it is no longer? That would be consistent with my findings at 1:
1. Personally I cannot reproduce this bug by setting Locale for my laptop, or running the test with VM options: -Duser.language=fr (or nl, for that matter). Only by explicitly setting the Locale in the test (see previous PR).
2. The original test does not validate that report.js is valid; it validates that an empty report throws a particular exception. I've renamed this test.
3. As suggested, I've added a test that does check for valid Javascript. I'm not sure this adds a lot of value, as other tests are also checking for valid js.
