### ISSUE TITLE
Would like JUnit ErrorCollector support or a Cucumber-jvm equivalent

### ISSUE THREAD

**Issue by JasonSmiley** [cucumber/cucumber-jvm#771]
I think this would be a common enough concern that it would work, however, I saw a post elsewhere saying this is not supported. (https://groups.google.com/forum/#!msg/cukes/qMwgAVzWmR0/GSkRUgJ8f4EJ)

I am ok with this not being supported at the moment, however, it seems like Error Collecting is something that any test developer would want.

Can we get this support inserted or get a cucumber equivalent?

**Comment by slaout** [comment]
Hello,

I've seen a lot of threads on the Web about people wanting to continue steps execution if one failed.
I've discussed with Cucumber developers: they think this is a bad idea: https://groups.google.com/forum/#!topic/cukes/xTqSyR1qvSc
Many times, scenarios can be reworked to avoid this need: scenarios must be split into several smaller and independent scenarios, or several checks can be aggregated into one, providing a more human scenario and a less script-like scenario.

But if you REALLY need this feature, like our project do, we've done a fork of Cucumber-JVM.
This fork let you annotate steps so that when they fail with a determined exception, they will let let next steps execute anyway (and the step itself is marked as failed).

The fork is available here:
https://github.com/slaout/cucumber-jvm/tree/continue-next-steps-for-exceptions-1.2.4
It's published on the OSSRH Maven repository.
See the README.md for usage, explanation screenshot and Maven dependency.
It's only available for the Java language, tough: any help is welcome to adapt the code to Ruby, for instance. I don't think it will be a lot of work.

Best regards,
Sébastien Laoût.

**Comment by lunivore** [comment]
Hi @JasonSmiley , I hope that the suggestions from the team have provided you with some different ways around your problem, or that the code mentioned here by @slaout is suitable for solving it. Since the team have indicated that they don't intend Cucumber-JVM to work in the way you describe (I support them in this), I am closing this ticket as a "won't fix". I hope you're enjoying your work with Cucumber-JVM!

**Comment by JasonSmiley** [comment]
No worries, I found a suitable workaround. Thanks for responding!

Sent from my iPhone

On Jun 28, 2017, at 8:40 AM, Liz Keogh <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi @JasonSmiley<https://github.com/jasonsmiley> , I hope that the suggestions from the team have provided you with some different ways around your problem, or that the code mentioned here by @slaout<https://github.com/slaout> is suitable for solving it. Since the team have indicated that they don't intend Cucumber-JVM to work in the way you describe (I support them in this), I am closing this ticket as a "won't fix". I hope you're enjoying your work with Cucumber-JVM!

**Comment by Dyadko** [comment]
Hi @JasonSmiley , could you share your workaround with me? I also stuck with this problem

**Comment by JasonSmiley** [comment]
I basically just wrote my own implementation by copy and pasting the error collector into my project, and then writing an after step to call the verify function (made public), and used the error collector as needed

Sent from my iPhone

On Oct 19, 2017, at 6:46 AM, Andrii Dvoinik <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi @JasonSmiley<https://github.com/jasonsmiley> , could you share your workaround with me? I also stuck with this problem

**Comment by slaout** [comment]
You mean an AfterStep like this: https://github.com/cucumber/cucumber/wiki/Hooks#step-hooks ?

So it only works with Ruby. No support in Java: see this issue: https://github.com/cucumber/cucumber-jvm/issues/604

**Comment by JasonSmiley** [comment]
Just for clarify, here is what I did:

1) I copy and paste this file into my project locally - https://github.com/junit-team/junit4/blob/master/src/main/java/org/junit/rules/ErrorCollector.java

2) In my local file, I made `verify()` a public function

3) in a `@Before` hook, I would instantiate the ErrorCollector, during my test I would use the `checkThat()` method, in the `@After` method I would call the verify().

```
private ErrorCollector collector;
@Before
public void setup(){
  collector = new ErrorCollector();
 // anything else you need in setup
}

@When("^Something should happen$")
public void stepExpample(){
  collector.checkThat("Something didn't happen", "something", equalTo("not something"));
}

@After
public void teardown(){
  collector.verify();
 // anything else you need in teardown
}
```
