### ISSUE TITLE
Javadoc stylesheet issue

### ISSUE THREAD

**Issue by jakecollins** [cucumber/cucumber-jvm#796]
Seem that the Javadoc stylesheet does not render links correctly in Chrome on Mac OS X. Many links are invisible until mouseover event. They become invisible again on mouseout.  

Affects top nav:

![image](https://cloud.githubusercontent.com/assets/2746448/4917417/d468dee6-64e4-11e4-834b-8825f0e47c9b.png)

![image](https://cloud.githubusercontent.com/assets/2746448/4917426/02972e12-64e5-11e4-869d-8c76e424f530.png)

And side nav:

![image](https://cloud.githubusercontent.com/assets/2746448/4917445/158cfdd0-64e5-11e4-82ee-c016ab624d76.png)

![image](https://cloud.githubusercontent.com/assets/2746448/4917451/1d6bec6e-64e5-11e4-91a2-f56419d43a76.png)

**Comment by mpkorstanje** [comment]
Okay. For this one we probably won't be able to reproduce this as the browsers have moved on. However for good measure we should update the maven plugin and check if it creates pretty javadoc.

The javadoc plugin is configured in the root pom.

Steps:
1. Figure out how to generate java doc (under java8)
2. Fix it till it works.

**Comment by mlvandijk** [comment]
maven-javadoc-plugin was just updated: https://github.com/cucumber/cucumber-jvm/commit/0ea7b433eed443abb314dbb01be920f0325af0e5

**Comment by mlvandijk** [comment]
Ad 1. Generate javadoc using command 'mvn javadoc:aggregate' (as mentioned in the genapi.sh)

Ad 2. Under java 8, maven fails to generate the javadoc if the javadoc tags are incomplete, apparently due to a new DocLint feature introduced in java8. This can be 'fixed' by ignoring the linting for java 8 (https://stackoverflow.com/questions/15886209/maven-is-not-working-in-java-8-when-javadoc-tags-are-incomplete/34809831#34809831)
It might be better to "fix"/improve the javadoc, but am not sure that doable... (as mentioned above)

3. The stylesheet issue:
(After generating docs as described above), I can reproduce this issue not only in Chrome but also on Firefox on OS X (and possibly other browsers) .
When replacing the current javadoc.css with a standard stylesheet.css for javadocs, the navigation does work.


Ad 3. Replaced the javadoc.css with a different stylesheet.css
Now the links etc work

**Comment by mpkorstanje** [comment]
>  It might be better to "fix"/improve the javadoc, but am not sure that doable... (as mentioned above)

It was doable so I've created #1211 that fixes this and adds it to the build. While I'm working on this, you can work on fixing the styling using the workaround you've found.
