### ISSUE TITLE
Cucumber Spring is not finding my step definitions

### ISSUE THREAD

**Issue by JasonSmiley** [cucumber/cucumber-jvm#835]
Since there is no great documentation on how to use this, I will admit I am possibly setting up my environment incorrectly. However, I can launch the WebApp (I see building of resources in console), I can see cucumber finding my features to execute, but when it tries to actually execute them, it says my steps are not defined and test is ignored.

My code can be found in this stack over flow question http://stackoverflow.com/questions/28466479/cucumber-spring-is-not-finding-step-definitions

To be honest, it looks like a bug in the cucumber to me at the moment, but since there is no good documentation on this, I can't tell if I am doing something wrong. Please advise!

currently using 1.2.2 Cucumber API

**Comment by aslakhellesoy** [comment]
I'm closing this issue since it sounds more like a question and not a bug report. Please see [CONTRIBUTING](https://github.com/cucumber/cucumber-jvm/blob/master/CONTRIBUTING.md) for details.

Feel free to reopen if you can share some code to reproduce, preferably in a GitHub repo.

**Comment by JasonSmiley** [comment]
It's a bug if my setup matches your example, which to me seems to be the case. If I am wrong, then agree. Sorry!

**Comment by aslakhellesoy** [comment]
Ok we'll see when you supply code to reproduce!

**Comment by JasonSmiley** [comment]
The code I am using is in the Stack Overflow.

Are you saying you need a github?

**Comment by brasmusson** [comment]
@JasonSmiley In your case the problems seems to be that you tried to use class (static) methods as step definitions ([as I answered on Stack Overflow](http://stackoverflow.com/a/28487156/4561043))

**Comment by JasonSmiley** [comment]
Thanks Brasmusson! I didn't realize you couldn't use static step definitions. In my Selenium cucumber project I use static functions all the time (so steps can call other steps easily).

Does this mean within a spring framework, I should just @autowire the step definitions and add beans to the cucumber.xml?

**Comment by JasonSmiley** [comment]
Just for the record, I checked out your cucumber examples project and couldn't even get it to compile!

**Comment by brasmusson** [comment]
@JasonSmiley That is really strange, because the spring-txn example is building and executing without problems on Travis, [here is the latest Travis log](https://travis-ci.org/cucumber/cucumber-jvm/jobs/47556711), from line 6785 is the output from the spring-txn example.

**Comment by JasonSmiley** [comment]
well, I checked out the full cucumber-jvm repo, opened spring-txn in intellije via the pom.xml, and then it couldn't compile - I thought it was funny because it didn't know what @CucumberOptions were....

Thanks so much for your support @brasmusson but I am going to give up on cucumber spring. I have already spent 2 days trying to get this to work and I can't waste anymore time on this.

**Comment by aslakhellesoy** [comment]
@JasonSmiley you must open the root pom

**Comment by brasmusson** [comment]
@JasonSmiley I copied the code from your question at stackoverflow and I basically find no problem with it with respect to "finding Step Definitions". I put it in a [GitHub project](https://github.com/brasmusson/spring-skeleton), you can try it yourself if you want (the GitHub project also include the [Cucumber-Java-Skeleton project](https://github.com/cucumber/cucumber-java-skeleton) changed to use cucumber-spring).

Some notes though:
 * The question "Cucumber-spring is not finding Step Definitions" is missleading, it is always cucumber-core that search for Step Definition, then cucumber-core passes the found Step Definition classes to the backend (and with cucumber-spring on the classpath, that would be cucumber-spring) with the intention "when I ask for a instance of any of this classes, create it for me please".
 *  Currently the glue parameter on the runner class (on StackOverflow page) is specified as `glue = "stepDefinitions.ItemServiceControllerTestsSteps"`, the glue parameter should specify base-package(s) for the search for Step Definition so it should be specified `glue = "stepDefinitions"` (I'm pretty sure it was that the first time I looked at the StackOverflow page).
 * I notice that the JUnit class has a `@WebAppConfiguration` annotation together with the `@ContextConfiguration` annotation, but the Step Definition class only has a `@ContextConfiguration` annotation. It has nothing to do with finding Step Definitions, but I you want to use whatever features the `@WebAppConfiguration` enables when running your features, you need to put it together with the `@ContextConfiguration` (or `@ContextHierarchy`) annotation on the Step Definition class with the `@ContextConfiguration` (or `@ContextHierarchy`) annotation.
 * Step Definition classes need a default constructor for the Spring Context to be able to instantiate them (as far as I can tell, I had to add one to the ItemServiceControllerTestsSteps to make it work)
 * Returning values from Step Definitions does not seem to ruin anything, but it is not useful since the value returned will not be used.
 * It seems that Step Definitions can be declared static, but the whole idea with Cucumber-JVM is that the Step Definition classes are created fresh for each Scenario.
 * To answer a questing on a comment you added and deleted here in this discussion. Yes, cucumber-spring can be used to connect different Step Definition class instances with `@Autowire`, see the example [here](https://github.com/brasmusson/spring-skeleton/blob/master/src/test/java/skeleton/Stepdefs2.java#L12-L21) were one Step Definition access a field on another Step Definition. Note that the Step Definition classes should not be declared a beans explicitly, cucumber-spring will add bean definition to the Spring Context itself, making sure that they get the scope `cucumber-glue` so they will be created fresh for each Scenario.

**Comment by JasonSmiley** [comment]
Updated my glue to "com.dibs.inventory.stepDefinitions" to match my step package.

Removed @Webapllication annotation from JUnit and cucumber (wasn't required)

Added default constructor.

Note: The return statement was for a demo I was giving to show that a step function could still be used in a traditional JUnit setting (not all developers I work with are comfortable using cucumber).

so just to clarify, cucumber.xml needs a bean line for each step definition?  That might explain why I am getting the following error:

java.lang.IncompatibleClassChangeError: Found class org.springframework.test.context.TestContext, but interface was expected
	at cucumber.runtime.java.spring.CucumberTestContextManager.getContext(SpringFactory.java:215)

**Comment by brasmusson** [comment]
@JasonSmiley You are not using Spring version 4, are you? I get the error:
```
java.lang.IncompatibleClassChangeError: Found class org.springframework.test.context.TestContext, but interface was expected
at cucumber.runtime.java.spring.CucumberTestContextManager.getContext(SpringFactory.java:215)
```
when using Spring v3.2.13 (I googled up https://github.com/springtestdbunit/spring-test-dbunit/issues/46 when searching for the error message). 
Cucumber-spring (v1.2.2) is built using Spring v4.1.4.RELEASE. Cucumber-JVM v1.1.5 was the last version built using Spring v3. However in versions v1.1.4-v1.1.8 Cucumber-spring had its share of issues (see #711), so I must recommend using Cucumber-JVM v1.2.x when using Spring.

No, cucumber.xml should not mention the step definition classes. But since Cucumber-spring adds bean definitions for them in the context, they can still `@Autowire` each other (in Cucumber-JVM v1.2.0 and later).

**Comment by JasonSmiley** [comment]
Ok, I am not sure if I will be able to update my spring version - I am writing a code for a spring project which is currently using 3.2.0.RELEASE so I will find out if there is a reason we haven't upgraded.

**Comment by brasmusson** [comment]
I guess that the options for using Spring v3 and Cucumber-JVM are:
 * Use Cucumber-JVM v1.1.3 (or maybe earlier):
   * `cucumber.xml` need to be named that and must be placed at the root of the classpath.
   * Do not use `@ContextConfiguration` annotations
   * `@Autowire` step definition classes to each other will work
   * The transaction support will work (add `cucumber.api.spring` to the glue paths and Before/After hooks will Start/Stop transactions).
   * The scope `cucumber-glue` will be available automatically in the spring context.
   * Annotations like `@WebAppConfiguration`, `@DirtiesContext`will not be taken into account.
   * The Pretty formatter will in v1.1.3 crash with a NullPointerException.
 * Use Cucumber-JVM v1.1.5 (or maybe v1.1.4):
   * Every step definition class needs a `@ContextConfiguration` annotation.
   * "`cucumber.xml`" is named in the `@ContextConfiguration` annotations, and does not need to be named that.
   * Annotations like `@WebAppConfiguration`, `@DirtiesContext`together with the `@ContextConfiguration` annotation will be honored.
   * `@Autowire` step definition classes to each other will not work.
   * The transaction support will not work.
   * The scope `cucumber-glue` need to explicitly added in the "`cucumber.xml`"

**Comment by JasonSmiley** [comment]
Thanks for this @brasmusson, I am going to push for upgrading our spring environment since I will be writing tests for the code, but in the meantime I am just going to be writing CRUD tests and I have been asked to write them Pure JUnit by the rest of the team. 

Eventually I will be writing Integration level tests and then cucumber will be much more important so I will make my decision on what cucumber to use then.
