### ISSUE TITLE
Rerun.txt format is currently broken (using maven) - doesn't run tests correctly when used as input

### ISSUE THREAD

**Issue by JasonSmiley208** [cucumber/cucumber-jvm#958]
So, when I generate a rerun.txt file via the rerun format:
`mvn clean test -Dcucumber.options="-t @rerun -p rerun:target/rerun.txt"`

and then pass this file into the maven runner:
`mvn test -Dcucumber.options="@target/rerun.txt"`

Then I get the following error:

> initializationError(runTest): Neither found on file system or on classpath: Not a file or directory: /Users/jason.smiley/Desktop/workspace/Cucumber-Tests/Rerun.feature, No resource found for: classpath:Rerun.feature

Note, the feature file actually lives in "Cucumber-Tests/src/test/java/features/Rerun.feature"

inside of the rerun.txt file is:

> Rerun.feature:10:13

Is this a usage error on my end? Or is this a bug with cucumber not writing src/test/java/features/Rerun.feature:10:13?

**Comment by JasonSmiley208** [comment]
So, I modified the file to use the full path to the feature file (src/test/java/features/Rerun.feature:10:13) and that got the tests running correctly. Is this a bug then?

**Comment by brasmusson** [comment]
There are limitations for workings of the rerun formatter and the usage of `@rerun.txt`.
What really works is to load the features from the classpath, that is:
```
mvn test -Dcucumber.options="-p rerun:rerun.txt classpath:some/path"
```
followed by:
```
mvn test -Dcucumber.options="@rerun.txt"
```
When loading features from a path on the file system, the limitations start to show up.
If I go to the [java-calculator example](https://github.com/cucumber/cucumber-jvm/tree/master/examples/java-calculator) and execute:
```
mvn test -Dcucumber.options="-p pretty src/test/resource"
```
one of the output lines is:
```
Scenario: Addition     # cucumber/examples/java/calculator/basic_arithmetic.feature:7
```
If I instead execute:
```
mvn test -Dcucumber.options="-p pretty src/test"
```
the corresponding output line becomes:
```
Scenario: Addition     # resource/cucumber/examples/java/calculator/basic_arithmetic.feature:7
```
When loading features from a path on the file system, the only path of the feature files that the rerun formatter, or any other formatter, is the path relative to the directory specified in the as argument to cucumber-jvm - so that is the path that is entered in `rerun.txt`.

To make the rerun feature work when loading features from a path on the file system, either the directory specified as argument to cucumber-jvm have to be the current directory (`mvn test -Dcucumber.options="."`), or one must go to the directory specified as argument to cucumber-jvm, before executing `mvn test -Dcucumber.options="@rerun.txt"`.

**Comment by JasonSmiley208** [comment]
I actually got this to work - I just put everything in the test/resource directory and that was sufficient for me.

Sorry... should have closed.
